### ISSUE TITLE
Inconsistent type signature in kubelet cadvisor clients causes compilation failure on OSX

### ISSUE THREAD

**Issue by liztio** [kubernetes/kubernetes#56082]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
> /kind feature

**What happened**:

We're working on a project which vendors some substantial parts of Kubernetes. After updating our vendored dependencies, I noticed that building locally (on my Macbook) failed, but building in a container succeeded. After some digging, I noticed a difference in type signature between [cadvisor_unsupported][unsupported] and [cadvisor_linux][linux] seemed to be causing the issue. The call site in [`cmd/kubelet/app`][server] unconditionally provides the extra boolean argument, causing compilation errors on OSX.

[unsupported]: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_unsupported.go#L34
[linux]: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L108
[server]: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L417

**What you expected to happen**:

I should be able to build this component on OSX. The type signature should match for all implementations of the cadvisor client, even if the argument is ignore.

**How to reproduce it (as minimally and precisely as possible)**:

```shell

$ cat failure_example.go
package main

import (
        "k8s.io/kubernetes/cmd/kubelet/app"
)

func main() {
        _ = app.componentKubelet
}
$ go install /tmp/failure_example.go
# k8s.io/kubernetes/cmd/kubelet/app
/Users/liz/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:417:49: too many arguments in call to cadvisor.New
        have (string, uint, cadvisor.ImageFsInfoProvider, string, bool)
        want (string, uint, cadvisor.ImageFsInfoProvider, string)
zsh: exit 2     go install /tmp/failure_example.go
go install /tmp/failure_example.go  5.84s user 1.47s system 131% cpu 5.542 total
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```shell
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.1
BuildVersion:   17B48
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Darwin kazkaan 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
```
- Install tools:
- Others:

**Comment by ncdc** [comment]
It looks like this was introduced by https://github.com/kubernetes/kubernetes/pull/55642 - FYI @dashpole

**Comment by dashpole** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/56002

**Comment by dashpole** [comment]
closing via https://github.com/kubernetes/kubernetes/pull/56003
