### PR TITLE
Fix build break on non-Linux OS introduced in 87aaf4c0

### PR DESCRIPTION
**Pull request by kad**
**What this PR does / why we need it**: simple fix for build breakage on non-Linux OS.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
**Special notes for your reviewer**:

```console
+++ [1102 11:16:58] linux/amd64: go build started
+++ [1102 11:20:11] linux/amd64: go build finished
+++ [1102 11:16:58] darwin/amd64: go build started
# k8s.io/kubernetes/pkg/kubelet/dockershim/cm
pkg/kubelet/dockershim/cm/container_manager_unsupported.go:33: undefined: fmt in fmt.Errorf
+++ [1102 11:16:58] windows/amd64: go build started
# k8s.io/kubernetes/pkg/kubelet/dockershim/cm
pkg/kubelet/dockershim/cm/container_manager_unsupported.go:33: undefined: fmt in fmt.Errorf
Makefile:79: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:255: recipe for target 'cross' failed
make: *** [cross] Error 1
Makefile:239: recipe for target 'release' failed
make: *** [release] Error 1
```

**Release note**:
```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36053)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by luxas** [comment]
@k8s-bot build this

**Comment by luxas** [comment]
Thanks @kad! LGTM

pinging @kubernetes/sig-testing => another cross-build failure
We really should make the cross-build test SQ-blocking soon

**Comment by spxtr** [comment]
https://github.com/kubernetes/test-infra/issues/951
