### PR TITLE
Automated cherry pick of #15014

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #15014 on release-1.1.

### CODE REVIEW

**Comment by ixdy** [comment]
The unit tests on release-1.1 were broken because #17302 was cherry-picked in #17452 but depended on #15014, which had not been cherry-picked:
```
_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go:256: too many arguments in call to WaitFor
FAIL	k8s.io/kubernetes/pkg/util/wait [build failed]
```

According to https://github.com/kubernetes/kubernetes/issues/14995#issuecomment-145094651, this should've been cherry-picked all along, so better late than never?

@ncdc @thockin @kubernetes/goog-testing

**Comment by ixdy** [comment]
@k8s-oncall can we find someone who's not OOO to review this? I'd like to get this in so we can stop continuously failing unit tests on 1.1.

**Comment by krousey** [comment]
@ixdy Did not realize that @brendandburns was OOO. Would this need a manual merge too since merge bot is blocked?
