### PR TITLE
apimachinery: add k8s-label-key format validation for Condition.Type

### PR DESCRIPTION
**Pull request by darshansreenivas**
/kind feature
/sig api-machinery

  #### What this PR does / why we need it:

   Migrates `metav1.Condition.Type` validation to Declarative Validation.

   This PR:
   - Adds a declarative validation tag to `Condition.Type`: `+k8s:format=k8s-label-key`
   - Marks the corresponding handwritten validation as covered by declarative validation
   - Adds declarative validation test coverage for invalid `Type` format values
   - Regenerates validation code and generated declarative validation tests

   #### Which issue(s) this PR is related to:

Part of #139638

Closes https://github.com/kubernetes/kubernetes/pull/139897

co-author @thesauravpoddar

### CODE REVIEW

**Comment by darshansreenivas** [comment]
cc @lalitc375

**Comment by darshansreenivas** [comment]
/remove rea/apiserver

area/code-generation

area/conformance

area/dependency

area/e2e-test-framework

area/ipvs

area/kube-proxy

area/kubeadm

**Comment by darshansreenivas** [comment]
/remove-area apiserver code-generation conformance dependency e2e-test-framework ipvs kube-proxy kubeadm kubectl kubelet provider/gcp release-eng stable-metrics test

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thesauravpoddar** [comment]
@lalitc375  @thockin Hiii i have already made a pr related to it #139897 can you please look at that and tell what's th problem so that i can fix

**Comment by darshansreenivas** [comment]
Hi @thesauravpoddar , thanks for working on the PR. We left review comments about three weeks ago, but there was no follow-up. The PR also included unnecessary tests for each resource, which would have required additional cleanup.

Since I needed to complete issue #139638 before the merge freeze, I finished the remaining work in the separate PR. I've added you as a co-author to acknowledge your contribution.

File: test/declarative_validation/certificates/podcertificaterequest/declarative_validation_test.go [hunk 1]
```diff
@@ -167,6 +167,17 @@ func TestDeclarativeValidateStatusUpdate(t *testing.T) {
...
 				},
+				{
+					Name: "invalid type",
+					Conditions: []metav1.Condition{
+						meta.MkCondition(meta.TweakType("-InvalidType")),
+					},
+					ExpectedErrs: field.ErrorList{
+						field.Invalid(field.NewPath("status", "conditions").Index(0).Child("type"), "-InvalidType", "").WithOrigin("format=k8s-label-key").MarkAlpha(),
+						// handwritten validation rejects any type outside the known set and uses .[0] notation
+						field.NotSupported(field.NewPath("status", "conditions").Child("[0]", "type"), "-InvalidType", []string{"Issued", "Denied", "Failed"}).MarkFromImperative(),
```
Comment (lalitc375) [inline test/declarative_validation/certificates/podcertificaterequest/declarative_validation_test.go]: Can we fix the notation in the source code?

**Comment by darshansreenivas** [comment]
@thesauravpoddar I tried reaching you on Slack but couldn’t find you. Unfortunately, we need to move forward with this PR for now. There will be plenty of opportunities to contribute to Declarative Validation in the future—and you’re already included as a co-author 🙂

**Comment by thockin** [comment]
@thesauravpoddar sorry for the confusion - since this is already approved, we should just close https://github.com/kubernetes/kubernetes/pull/139897 unless you have some important reason they are different?

**Comment by thesauravpoddar** [comment]
> and

Okay understood and thanks for mentioning me as a co-author

**Comment by thesauravpoddar** [comment]
> @thesauravpoddar sorry for the confusion - since this is already approved, we should just close https://github.com/kubernetes/kubernetes/pull/139897 unless you have some important reason they are different?

Okay understood

File: test/declarative_validation/certificates/podcertificaterequest/declarative_validation_test.go (hunk 1 above)
Comment (darshansreenivas) [reply test/declarative_validation/certificates/podcertificaterequest/declarative_validation_test.go]: Sure, sounds good.

**Comment by huww98** [comment]
Heads-up: this PR is now red against `master` because of a merge skew with #137050 (EvictionRequest API), which merged after this PR's last verified presubmit run.

The failing [batch](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/batch/pull-kubernetes-unit/2080106163034132480) (`pull-kubernetes-unit`) shows:

```
=== RUN   TestValidateEvictionRequestStatusUpdate/add_invalid_condition
    validation_test.go:213: Error 0: expected CoveredByDeclarative=false, got true for error: status.conditions[0].type: Invalid value: "-bad-name": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
--- FAIL: TestValidateEvictionRequestStatusUpdate/add_invalid_condition (0.00s)
=== RUN   TestValidateEvictionRequestStatusUpdate
--- FAIL: TestValidateEvictionRequestStatusUpdate (0.00s)
=== RUN   TestValidateEvictionStatusUpdate/add_invalid_condition
    validation_test.go:1652: Error 0: expected CoveredByDeclarative=false, got true for error: status.conditions[0].type: Invalid value: "-bad-name": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
--- FAIL: TestValidateEvictionStatusUpdate/add_invalid_condition (0.00s)
=== RUN   TestValidateEvictionStatusUpdate
--- FAIL: TestValidateEvictionStatusUpdate (0.01s)
```

Root cause: this PR adds `.MarkCoveredByDeclarative()` to the `Condition.Type` error in the shared `metav1validation.ValidateCondition`. #137050's validation test (`pkg/apis/lifecycle/validation/validation_test.go`) matches with `ErrorMatcher{}.ByType().ByField().ByDetailSubstring()`, which doesn't compare `CoveredByDeclarative` — but a separate hand-rolled loop does, against expected errors built as plain `field.Invalid(...)` that default to `false`, so the newly-marked `type` error no longer matches. That test didn't exist on this branch when it last ran presubmit, so CI couldn't have caught it.

The [`pull-kubernetes-verify`](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/batch/pull-kubernetes-verify/2080106163315150848) job in the same batch fails for the same reason, via codegen: this PR's `.WithOrigin("format=k8s-label-key")` changes what `hack/update-codegen.sh` emits for #137050's new declarative-validation tests, but those files (`test/declarative_validation/lifecycle/{eviction,evictionrequest}/zz_generated.validations.v1alpha1_test.go`) didn't exist on this branch, so they weren't regenerated:

```
    "status.conditions[*].type": {
+       {ErrorType: "FieldValueInvalid", Origin: "format=k8s-label-key"},
        {ErrorType: "FieldValueRequired"},
    },
```

Holding so it doesn't stall the PR merge queue.

/hold

**Comment by atiratree** [comment]
Sorry for the conflict. The EvictionRequest and Eviction tests have been validating conditions for the fields that have not been covered declaratively.

You can simply update the test by changing the name https://github.com/kubernetes/kubernetes/blob/f99d91b8851300d7dc3856903232873d509b1425/pkg/apis/lifecycle/validation/validation_test.go#L853 and removing the error
https://github.com/kubernetes/kubernetes/blob/f99d91b8851300d7dc3856903232873d509b1425/pkg/apis/lifecycle/validation/validation_test.go#L860

**Comment by huww98** [comment]
/skip
trying to clear all those stall test results

File: pkg/apis/lifecycle/validation/validation_test.go [hunk 2]
```diff
@@ -850,14 +850,13 @@ func TestValidateEvictionStatusUpdate(t *testing.T) {
 			oldInput: mkValidEvictionStatus(1),
 			input: mkValidEvictionStatus(1, func(obj *lifecycle.EvictionStatus) {
 				obj.Conditions = append(obj.Conditions, metav1.Condition{
-					Type:               "-bad-name",
+					Type:               "bad-name",
```
Comment (atiratree) [inline pkg/apis/lifecycle/validation/validation_test.go]: nit
```suggestion
					Type:               "good-name",
```

Comment (atiratree) [reply pkg/apis/lifecycle/validation/validation_test.go]: btw we need to do the same fix in `TestValidateEvictionRequestStatusUpdate`

File: staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go [hunk 3]
```diff
@@ -1650,6 +1650,7 @@ type Condition struct {
 	// +kubebuilder:validation:Pattern=`^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$`
 	// +kubebuilder:validation:MaxLength=316
 	// +k8s:alpha(since: "1.37")=+k8s:required
+	// +k8s:alpha(since: "1.37")=+k8s:format=k8s-label-key
```
Comment (yongruilin) [inline staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go:1653]: As this PR didn't get into 1.37, should change to 1.38 moving forward.

/hold wait for https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/version/base.go#L63 gets updated to `1.38`

**Review by yongruilin — COMMENTED** [review]
One nit.

**Review by yongruilin — COMMENTED** [review]
/lgtm
/hold cancel
