### PR TITLE
e2e: move AllNodesReady check to DeferCleanup

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Some test cases can make nodes not ready and use DeferCleanup to bring nodes back online. Checking if all nodes are online would fail in such cases as `ginkgo.AfterEach` runs before `ginkgo.DeferCleanup`.

Scheduling nodes readines check to DeferCleanup should solve this issue as nodes would be brought back to a `Ready` state before the check.

#### Special notes for your reviewer:

This issue was discovered when working on [DRA: e2e: test non-graceful node shutdown](https://github.com/kubernetes/kubernetes/pull/120965) and the fix was suggested by @pohly

See more details [in this comment](https://github.com/kubernetes/kubernetes/pull/120965#discussion_r1347572940)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @pohly 
(for lgtm)
/approve

**Comment by aojea** [comment]
/hold 

I like @pohly to sign off if you don't mind, I don't have clear  the comment referenced means to change this part

> You can move all of this into the DeferCleanup above. A cleanup callback can fail just like the It callback and it will make the test as failed.

**Comment by aojea** [comment]
also , I don't like to change the e2e framework to support kind clusters, please let's discuss this

**Comment by bart0sh** [comment]
> also , I don't like to change the e2e framework to support kind clusters, please let's discuss this

It's not about supporting kind clusters. It's about supporting node shutdowns. We can do the same by killing Kubelet on a node.

**Comment by aojea** [comment]
> It's not about supporting kind clusters. It's about supporting node shutdowns. We can simulate node shutdown for a standard e2e setup (without kind) by killing `Kubelet` on a node. And without this change the test will take 7 minutes longer even if we do `Kubelet` restart in the `DeferCleanup`.

The e2e framework should not perform operations on the cluster, it does because of historical reasons, but I don't think that is something we should keep building on that ... I think we can explore different options for chaos testing, I think that there is also some code somewhere, but I do not think should bring those things to the e2e framework ... it can be a different framework

**Comment by bart0sh** [comment]
@aojea 
> The e2e framework should not perform operations on the cluster

This change doesn't make any cluster operations. It does 2 things:
- moves node readiness check to DeferCleanup
- makes the check stricter by checking its return value (it's ignored in the current version)

File: test/e2e/framework/node/init/init.go [hunk 1]
```diff
@@ -31,13 +32,9 @@ func init() {
...
 		func(f *framework.Framework) {
 			ginkgo.AfterEach(func(ctx context.Context) {
-				if f.ClientSet == nil {
-					// Test didn't reach f.BeforeEach, most
-					// likely because the test got
-					// skipped. Nothing to check...
-					return
-				}
-				e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
+				ginkgo.DeferCleanup(func() {
```
Comment (aojea) [inline test/e2e/framework/node/init/init.go:35]: I'm reading the docs https://onsi.github.io/ginkgo/#spec-cleanup-aftereach-and-defercleanup and I don't understand from there how is this supposed to work , to use DeferCleanup inside AfterEach sounds at least very hard to reason about

File: test/e2e/framework/node/init/init.go [hunk 2]
```diff
@@ -31,13 +32,9 @@ func init() {
 	framework.NewFrameworkExtensions = append(framework.NewFrameworkExtensions,
 		func(f *framework.Framework) {
 			ginkgo.AfterEach(func(ctx context.Context) {
-				if f.ClientSet == nil {
```
Comment (aojea) [inline test/e2e/framework/node/init/init.go:34]: why do we need to remove this check?

Comment (bart0sh) [reply test/e2e/framework/node/init/init.go:34]: Because we don't need it anymore. ClientSet attribute is initialized in the [framework.BeforeEach](https://github.com/kubernetes/kubernetes/blob/release-1.28/test/e2e/framework/framework.go#L233), so it's guaranteed that it's not nil when deferred cleanup callbacks are called. Moreover, it's checked in the [framework.AfterEach](https://github.com/kubernetes/kubernetes/blob/release-1.28/test/e2e/framework/framework.go#L347) anyway.

File: test/e2e/framework/node/init/init.go (hunk 1 above)
Comment (bart0sh) [reply test/e2e/framework/node/init/init.go:35]: I agree, it's a bit hard to understand, but essentially this code schedules node readiness check  a bit further in time, after all other deferred cleanup callbacks. From my point of view it makes perfect sense and gives test cases an ability to restore node state in their deferred cleanup callback if they change it for the test purposes.

Comment (bart0sh) [reply test/e2e/framework/node/init/init.go:35]: One thing in the above mentioned doc that worth pointing out here:
```
Under the hood DeferCleanup is generating a dynamic AfterEach node and adding it to the running spec. 
```
So, this code generates dynamic `AfterEach`, which will be called later, allowing `DeferCleanup`s created by the test case to do their work.

**Comment by aojea** [comment]
Ed let me try to summarize my reading of the situation
1. there is an e2e test that uses kind that will need this change
2. in addition, you mention that e2e node tests that restarts kubelet will benefit from this

The e2e framework and all e2e tests must be agnostic of the infrastructure, so tests are hermetic and portable, I know is not true today for historical reasons, be we are in much better shape than before now and I don't like us to make the same mistake again. I do not how widespread is the kind usage on e2e tests but I expect this is targeted and well encapsulated.

This change introduces important changes on behavior, with a convoluted solution based on defers inside afterach actions. Also, starts to assert on the node state,  and tests must assert on the test itself not in the infrastructure, it will not be ok that a test that assert on Services and passes fails later because the cluster uses autoscaler or similar thing and one of the nodes is not ready, we are not validating the cluster, we are testing a Kubernetes feature end to end.

I really appreciate all your hard work you are doing and I want to help you to solve the problem, we can talk more on the next sig-testing meeting or on slack, and try to find alternatives that solve your problem, but we need a stronger argument to change an existing behavior of the e2e test, the blast radius is huge impacting multiple companies and users and takes a long time to impact them, so the fixes are harder to implement later.

**Comment by bart0sh** [comment]
> there is an e2e test that uses kind that will need this change

That's correct, but there are at least 2 other solutions for that particular issue, so it's not a big deal at all.

> in addition, you mention that e2e node tests that restarts kubelet will benefit from this

I was talking about e2e tests. e2e node doesn't have any problems with stopping and starting Kubelet. However, e2e does, if I'm not mistaken.

> The e2e framework and all e2e tests must be agnostic of the infrastructure

If this means that tests shouldn't be able to stop a node even for test purposes, then I'd agree that this PR doesn't make much sense. However, I doubt this is the case, considering existence of [framework.node.NodeKiller](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/node/node_killer.go) and [node shutdown tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/non_graceful_node_shutdown.go).

> This change introduces important changes on behavior, with a convoluted solution based on defers inside afterach actions.

I'd agree with this - there should be a better way to do it. May be we should consider moving node readiness check out of `AfterEach` to the same level where nodes are usually created. In its current form the check doesn't make sense as it only slows down the overall test workflow if one of the nodes is not ready. We should either remove it or make it stricter.

> we need a stronger argument to change an existing behavior of the e2e test

I'd agree with this as well. Just need to understand the whole idea of expecting all test nodes to be ready, but not failing the test if they're not ready. Can you explain?

I tend to close this PR as there are other ways to solve the slowness issue discovered in  https://github.com/kubernetes/kubernetes/pull/120965. I'd appreciate though if you answer these 2 questions:
- does e2e framework expect that nodes can't be stopped during the test?
- if we don't expect the nodes to be ready what's the purpose of [this code](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/node/init/init.go#L40)

Sure, we can discuss it on Slack if needed.

**Comment by aojea** [comment]
> does e2e framework expect that nodes can't be stopped during the test?

That is a disruptive test, we have a tag for that  the main problem here is how to do that in a way that works in all environments, see all the problems are having the people is trying to add kops now as presubmit, there are some tests that assume kube-up scripts, that is wrong , checking at this particular method nodeKiller that you mentioning, it assumes docker and ssh works , that is not really good because docker is no longer present and ssh access is not guaranteed and I don't think is something we must enforce to run e2e tests

https://github.com/kubernetes/kubernetes/blob/8e8ac86cf1118ddce2693aa8481dd02dab1385e3/test/e2e/framework/node/node_killer.go#L76-L77

Don't let existing things that are wrong to stop us to keep improving ;) If we want to add some chaos testing or disruptive testing, let's do it right, with a proper API so everybody can run them ... is a nice project and I'm happy to review a KEP for implementing that

> if we don't expect the nodes to be ready what's the purpose of [this code](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/node/init/init.go#L40) ?

That predates 1.0 version https://github.com/kubernetes/kubernetes/pull/11008

I joined the project in 2019, there are a lot of thing that need historical contexts and a lot of people from these days is no longer present in the project. There are functions and things that are there but no longer used, or were added because of X reasons that no longer apply.

The only I can say from my experience all these years, everytime we do a subtle change that modify a behavior it bit us back, with significant consequences

**Comment by bart0sh** [comment]
@aojea Thank you for the detailed explanations!

One last thing before closing this PR. https://github.com/kubernetes/kubernetes/pull/11008 introduced proper check that fails a test if any of the test nodes is not ready. Current code doesn't do it. The only outcome of it is an error message buried in a usually super-verbose ginkgo output and a 7 minutes(!!!) timeout slowing down the tests. Would it make sense to remove it as a useless legacy code or it has some hidden benefits I didn't get/missed?

File: test/e2e/framework/node/init/init.go (hunk 1 above)
Comment (pohly) [reply test/e2e/framework/node/init/init.go:35]: @bart0sh: this is not what we discussed in our chat last week. There I suggested 
```
ginkgo.BeforeEach(func() {
    gingko.DeferCleanup(func() {
        e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
    })
})
```
as replacement for the current `AfterEach`.

With my proposal, the `DeferCleanup` gets called before any code provided by a test, and because of the first-in-last-out order for `DeferCleanup`, the test is able to do whatever is necessary to make nodes ready again in its own `DeferCleanup`.

With your combination of `BeforeEach` + `DeferCleanup`, the `DeferCleanup` gets callback gets register *after* the test's callback and then gets invoked *before* the test's cleanup - not what we want to achieve.

**Comment by pohly** [comment]
> Current code doesn't do it. The only outcome of it is an error message buried in a usually super-verbose ginkgo output and a 7 minutes(!!!) timeout slowing down the tests.

I think we should turn this error message into a test failure.

**Comment by pohly** [comment]
Let's compare the different approaches. Current state, with this path applied to illustrate ordering:
```patch
diff --git a/test/e2e/dra/dra.go b/test/e2e/dra/dra.go
index 3f803c3db12..958c75a98d5 100644
--- a/test/e2e/dra/dra.go
+++ b/test/e2e/dra/dra.go
@@ -51,6 +51,28 @@ func networkResources() app.Resources {
 	}
 }
 
+var _ = ginkgo.Describe("test", func() {
+	framework.NewDefaultFramework("dra")
+
+	ginkgo.BeforeEach(func() {
+		framework.Logf("test before each")
+		ginkgo.DeferCleanup(func() {
+			framework.Logf("test cleanup 1")
+		})
+	})
+
+	ginkgo.AfterEach(func() {
+		framework.Logf("test after each")
+	})
+
+	ginkgo.It("it", func() {
+		framework.Logf("test it")
+		ginkgo.DeferCleanup(func() {
+			framework.Logf("test cleanup 2")
+		})
+	})
+})
+
 var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", func() {
 	f := framework.NewDefaultFramework("dra")
 
diff --git a/test/e2e/framework/node/init/init.go b/test/e2e/framework/node/init/init.go
index 653eb6bdebc..be696e81fa9 100644
--- a/test/e2e/framework/node/init/init.go
+++ b/test/e2e/framework/node/init/init.go
@@ -37,6 +37,7 @@ func init() {
 					// skipped. Nothing to check...
 					return
 				}
+				framework.Logf("framework: all nodes ready")
 				e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
 			})
 		},
```

```
  Oct 16 16:10:20.448: INFO: test before each
  Oct 16 16:10:20.449: INFO: test it
  Oct 16 16:10:20.449: INFO: framework: all nodes ready
  Oct 16 16:10:20.449: INFO: Waiting up to 7m0s for all (but 0) nodes to be ready
  Oct 16 16:10:20.452: INFO: test after each
  Oct 16 16:10:20.452: INFO: test cleanup 2
  Oct 16 16:10:20.452: INFO: test cleanup 1
```

This is bad, framework code runs interleaved.

Now with `AfterEach` + `DeferCleanup`:
```patch
diff --git a/test/e2e/dra/dra.go b/test/e2e/dra/dra.go
index 3f803c3db12..958c75a98d5 100644
--- a/test/e2e/dra/dra.go
+++ b/test/e2e/dra/dra.go
@@ -51,6 +51,28 @@ func networkResources() app.Resources {
 	}
 }
 
+var _ = ginkgo.Describe("test", func() {
+	framework.NewDefaultFramework("dra")
+
+	ginkgo.BeforeEach(func() {
+		framework.Logf("test before each")
+		ginkgo.DeferCleanup(func() {
+			framework.Logf("test cleanup 1")
+		})
+	})
+
+	ginkgo.AfterEach(func() {
+		framework.Logf("test after each")
+	})
+
+	ginkgo.It("it", func() {
+		framework.Logf("test it")
+		ginkgo.DeferCleanup(func() {
+			framework.Logf("test cleanup 2")
+		})
+	})
+})
+
 var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", func() {
 	f := framework.NewDefaultFramework("dra")
 
diff --git a/test/e2e/framework/node/init/init.go b/test/e2e/framework/node/init/init.go
index 653eb6bdebc..ec26fd34b3a 100644
--- a/test/e2e/framework/node/init/init.go
+++ b/test/e2e/framework/node/init/init.go
@@ -31,13 +31,11 @@ func init() {
 	framework.NewFrameworkExtensions = append(framework.NewFrameworkExtensions,
 		func(f *framework.Framework) {
 			ginkgo.AfterEach(func(ctx context.Context) {
-				if f.ClientSet == nil {
-					// Test didn't reach f.BeforeEach, most
-					// likely because the test got
-					// skipped. Nothing to check...
-					return
-				}
-				e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
+				framework.Logf("framework: after each")
+				ginkgo.DeferCleanup(func() {
+					framework.Logf("framework: all nodes ready")
+					e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
+				})
 			})
 		},
 	)
```

```
  Oct 16 16:13:21.973: INFO: test before each
  Oct 16 16:13:21.973: INFO: test it
  Oct 16 16:13:21.973: INFO: framework: after each
  Oct 16 16:13:21.973: INFO: test after each
  Oct 16 16:13:21.973: INFO: framework: all nodes ready
  Oct 16 16:13:21.973: INFO: Waiting up to 7m0s for all (but 0) nodes to be ready
  Oct 16 16:13:21.973: INFO: test cleanup 2
  Oct 16 16:13:21.973: INFO: test cleanup 1
```

Still not what we want.

Here's my proposal:
```patch
diff --git a/test/e2e/dra/dra.go b/test/e2e/dra/dra.go
index 3f803c3db12..958c75a98d5 100644
--- a/test/e2e/dra/dra.go
+++ b/test/e2e/dra/dra.go
@@ -51,6 +51,28 @@ func networkResources() app.Resources {
 	}
 }
 
+var _ = ginkgo.Describe("test", func() {
+	framework.NewDefaultFramework("dra")
+
+	ginkgo.BeforeEach(func() {
+		framework.Logf("test before each")
+		ginkgo.DeferCleanup(func() {
+			framework.Logf("test cleanup 1")
+		})
+	})
+
+	ginkgo.AfterEach(func() {
+		framework.Logf("test after each")
+	})
+
+	ginkgo.It("it", func() {
+		framework.Logf("test it")
+		ginkgo.DeferCleanup(func() {
+			framework.Logf("test cleanup 2")
+		})
+	})
+})
+
 var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", func() {
 	f := framework.NewDefaultFramework("dra")
 
diff --git a/test/e2e/framework/node/init/init.go b/test/e2e/framework/node/init/init.go
index 653eb6bdebc..d570d177831 100644
--- a/test/e2e/framework/node/init/init.go
+++ b/test/e2e/framework/node/init/init.go
@@ -30,14 +30,12 @@ import (
 func init() {
 	framework.NewFrameworkExtensions = append(framework.NewFrameworkExtensions,
 		func(f *framework.Framework) {
-			ginkgo.AfterEach(func(ctx context.Context) {
-				if f.ClientSet == nil {
-					// Test didn't reach f.BeforeEach, most
-					// likely because the test got
-					// skipped. Nothing to check...
-					return
-				}
-				e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
+			ginkgo.BeforeEach(func(ctx context.Context) {
+				framework.Logf("framework: before each")
+				ginkgo.DeferCleanup(func() {
+					framework.Logf("framework: all nodes ready")
+					e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
+				})
 			})
 		},
 	)
```

```

**Comment by pohly** [comment]
> > Current code doesn't do it. The only outcome of it is an error message buried in a usually super-verbose ginkgo output and a 7 minutes(!!!) timeout slowing down the tests.
> 
> I think we should turn this error message into a test failure.

There is missing error checking:
```
ERROR: test/e2e/framework/node/init/init.go:37:27: Error return value of `e2enode.AllNodesReady` is not checked (errcheck)
ERROR: 					e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
ERROR: 					                     ^
```

I accidentally dropped the error checking when moving the node support code out of the core framework in 1.26. If we had had today's golangci-lint checks, it would have been flagged as a problem. Because we didn't, it was overlooked... Sorry about that!

**Comment by bart0sh** [comment]
@pohly I've updated this PR as you've suggested and tested it with 'must deallocate on non graceful node shutdown' DRA test case. It worked. Please, review.

File: test/e2e/framework/node/init/init.go [hunk 3]
```diff
@@ -30,14 +31,10 @@ import (
...
-			ginkgo.AfterEach(func(ctx context.Context) {
-				if f.ClientSet == nil {
-					// Test didn't reach f.BeforeEach, most
-					// likely because the test got
-					// skipped. Nothing to check...
-					return
-				}
-				e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
+			ginkgo.BeforeEach(func(ctx context.Context) {
+				ginkgo.DeferCleanup(func(ctx context.Context) {
```
Comment (aojea) [inline test/e2e/framework/node/init/init.go:35]: ok, this is the same as in 

https://github.com/kubernetes/kubernetes/blob/64799e076097cf3c3dd12a82f9593a9bd57f042e/test/e2e/framework/framework.go#L209-L215

and easier to think about

File: test/e2e/framework/node/init/init.go [hunk 4]
```diff
@@ -30,14 +31,10 @@ import (
...
+					gomega.Expect(e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)).To(gomega.Succeed())
```
Comment (aojea) [inline test/e2e/framework/node/init/init.go:36]: this things make me nervous, please triple check we were asserting before and it got removed

File: test/e2e/framework/node/init/init.go (hunk 2 above)
Comment (aojea) [reply test/e2e/framework/node/init/init.go:34]: sames, please triple check we don't need to keep check we don't need it, the comment mentions that if is skipped it can reach here, I don't know if it is possible, @pohly do you know?

**Comment by aojea** [comment]
/hold cancel

Wait for @pohly for lgtm and please double check my last comments, these init() function inside the framework that adds hooks are super tricky to debug

File: test/e2e/framework/node/init/init.go (hunk 4 above)
Comment (bart0sh) [reply test/e2e/framework/node/init/init.go:36]: Thanks, I'll try to check it out. However, @pohly mentioned [here](https://github.com/kubernetes/kubernetes/pull/121139#issuecomment-1764665612) that he removed the error checking by accident.

File: test/e2e/framework/node/init/init.go (hunk 2 above)
Comment (pohly) [reply test/e2e/framework/node/init/init.go:34]: That was true when the code ran in `AfterEach` and the reason why it [was added](https://github.com/kubernetes/kubernetes/commit/3c162af45fa6a874b510015534835b74c30cc60b).

But now it's in a `BeforeEach` and that does not run for skipped tests (I checked!), so the original reason no longer applies and the `if` check isn't needed anymore. We shouldn't keep code around "just in case".

**Review by pohly — CHANGES_REQUESTED** [review]

File: test/e2e/framework/node/init/init.go [hunk 5]
```diff
@@ -30,14 +31,10 @@ import (
...
 		func(f *framework.Framework) {
-			ginkgo.AfterEach(func(ctx context.Context) {
-				if f.ClientSet == nil {
-					// Test didn't reach f.BeforeEach, most
-					// likely because the test got
-					// skipped. Nothing to check...
-					return
-				}
-				e2enode.AllNodesReady(ctx, f.ClientSet, 7*time.Minute)
+			ginkgo.BeforeEach(func(ctx context.Context) {
```
[the remark this answers is not in the document]
Comment (bart0sh) [reply test/e2e/framework/node/init/init.go]: done

**Review by pohly — APPROVED** [review]
Looks good to me, but I don't want to merge it if @aojea doesn't agree. @aojea, can you do the lgtm to confirm?

/approve

**Comment by aojea** [comment]
We solve one regression and we replace an AfterEach with a BeforeEach that hooks a DeferCleanup so it runs just where we want

/lgtm

Thanks for the healthy discussion
