### ISSUE TITLE
go mod tidy fails in kubernetes/kubernetes on go1.13

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#82506]
https://github.com/golang/go/wiki/Modules#how-to-prepare-for-a-release specifies that we should run `go mod tidy` before a release to ensure our `go.mod` file is limited to the set of imports we actually need.

However this currently fails:
```console
$ go mod tidy
warning: ignoring symlink /usr/local/google/home/fejta/src/gh/kubernetes/bazel-bin
warning: ignoring symlink /usr/local/google/home/fejta/src/gh/kubernetes/bazel-genfiles
warning: ignoring symlink /usr/local/google/home/fejta/src/gh/kubernetes/bazel-kubernetes
warning: ignoring symlink /usr/local/google/home/fejta/src/gh/kubernetes/bazel-out
warning: ignoring symlink /usr/local/google/home/fejta/src/gh/kubernetes/bazel-testlogs
warning: ignoring symlink /usr/local/google/home/fejta/src/gh/kubernetes/cluster/gce/cos
warning: ignoring symlink /usr/local/google/home/fejta/src/gh/kubernetes/cluster/gce/custom
warning: ignoring symlink /usr/local/google/home/fejta/src/gh/kubernetes/cluster/gce/ubuntu
go: downloading golang.org/x/time v0.0.0-20161028155119-f51c12702a4d
go: downloading golang.org/x/crypto v0.0.0-20181025213731-e84da0312774
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading golang.org/x/sys v0.0.0-20190209173611-3b5209105503
go: extracting golang.org/x/time v0.0.0-20161028155119-f51c12702a4d
go: downloading golang.org/x/lint v0.0.0-20181217174547-8f45f776aaf1
go: extracting golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: extracting golang.org/x/lint v0.0.0-20181217174547-8f45f776aaf1
go: extracting golang.org/x/crypto v0.0.0-20181025213731-e84da0312774
go: extracting golang.org/x/sys v0.0.0-20190209173611-3b5209105503
go: downloading golang.org/x/text v0.3.1-0.20181227161524-e6919f6577db
go: downloading golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: extracting golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: extracting golang.org/x/text v0.3.1-0.20181227161524-e6919f6577db
k8s.io/kubernetes/kubernetes/cluster/images/etcd/migrate imports
	k8s.io/kubernetes/third_party/forked/etcd221/wal: cannot find module providing package k8s.io/kubernetes/third_party/forked/etcd221/wal
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes imports
	k8s.io/kubernetes/pkg/api: cannot find module providing package k8s.io/kubernetes/pkg/api
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes imports
	k8s.io/kubernetes/pkg/api/v1: cannot find module providing package k8s.io/kubernetes/pkg/api/v1
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes imports
	k8s.io/kubernetes/pkg/client/clientset_generated/clientset: cannot find module providing package k8s.io/kubernetes/pkg/client/clientset_generated/clientset
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes imports
	k8s.io/kubernetes/pkg/volume/util/volumehelper: cannot find module providing package k8s.io/kubernetes/pkg/volume/util/volumehelper
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/executors/kubeexec imports
	github.com/heketi/heketi/pkg/remoteexec/kube imports
	k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1: cannot find module providing package k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/executors/kubeexec imports
	github.com/heketi/heketi/pkg/remoteexec/kube imports
	k8s.io/kubernetes/pkg/client/unversioned/remotecommand: cannot find module providing package k8s.io/kubernetes/pkg/client/unversioned/remotecommand
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes tested by
	github.com/heketi/heketi/pkg/kubernetes.test imports
	k8s.io/kubernetes/pkg/client/clientset_generated/clientset/fake: cannot find module providing package k8s.io/kubernetes/pkg/client/clientset_generated/clientset/fake
```

Slightly hard to understand how to parse this output. Are these due to circular dependencies?

ref https://github.com/kubernetes/kubernetes/issues/81878

**Comment by liggitt** [comment]
we run `go mod tidy` in this repo as part of `hack/update-vendor.sh`

What version of go are you running?

**Comment by liggitt** [comment]
And is that on a clean working directory?

**Comment by liggitt** [comment]
See 

https://github.com/kubernetes/kubernetes/blob/6348200c92dec8848e55552f3e8039b3da95bd91/hack/update-vendor.sh#L296-L297

**Comment by fejta** [comment]
I believe so?

```console
$ git reset --hard HEAD
HEAD is now at 6348200c92 Merge pull request #82501 from losipiuk/lo/ca-1.16-final
fejta@fejta3:~/src/gh/kubernetes$ git status
On branch rbe
nothing to commit, working tree clean
fejta@fejta3:~/src/gh/kubernetes$ git log
commit 6348200c92dec8848e55552f3e8039b3da95bd91 (HEAD -> rbe, upstream/master, origin/master, origin/HEAD)
Merge: 35cf6b6cbc b27e0b54f1
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Mon Sep 9 14:12:54 2019 -0700

    Merge pull request #82501 from losipiuk/lo/ca-1.16-final
    
    Update Cluster Autoscaler version to 1.16.0
fejta@fejta3:~/src/gh/kubernetes$ go mod tidy
```

**Comment by fejta** [comment]
Will try on a clean VM using both go1.12 and go1.13

**Comment by fejta** [comment]
Works on 1.12, fails on 1.13:

```console
fejta@erick:~/kubernetes$ ~/go1.12/bin/go mod tidy
warning: ignoring symlink /home/fejta/kubernetes/cluster/gce/cos
warning: ignoring symlink /home/fejta/kubernetes/cluster/gce/custom
warning: ignoring symlink /home/fejta/kubernetes/cluster/gce/ubuntu
fejta@erick:~/kubernetes$ ~/go1.13/bin/go mod tidy
warning: ignoring symlink /home/fejta/kubernetes/cluster/gce/cos
warning: ignoring symlink /home/fejta/kubernetes/cluster/gce/custom
warning: ignoring symlink /home/fejta/kubernetes/cluster/gce/ubuntu
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes imports
	k8s.io/kubernetes/pkg/api: cannot find module providing package k8s.io/kubernetes/pkg/api
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes imports
	k8s.io/kubernetes/pkg/api/v1: cannot find module providing package k8s.io/kubernetes/pkg/api/v1
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes imports
	k8s.io/kubernetes/pkg/client/clientset_generated/clientset: cannot find module providing package k8s.io/kubernetes/pkg/client/clientset_generated/clientset
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes imports
	k8s.io/kubernetes/pkg/volume/util/volumehelper: cannot find module providing package k8s.io/kubernetes/pkg/volume/util/volumehelper
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/executors/kubeexec imports
	github.com/heketi/heketi/pkg/remoteexec/kube imports
	k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1: cannot find module providing package k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/executors/kubeexec imports
	github.com/heketi/heketi/pkg/remoteexec/kube imports
	k8s.io/kubernetes/pkg/client/unversioned/remotecommand: cannot find module providing package k8s.io/kubernetes/pkg/client/unversioned/remotecommand
k8s.io/kubernetes/pkg/volume/glusterfs imports
	github.com/heketi/heketi/client/api/go-client tested by
	github.com/heketi/heketi/client/api/go-client.test imports
	github.com/heketi/heketi/apps/glusterfs imports
	github.com/heketi/heketi/pkg/kubernetes tested by
	github.com/heketi/heketi/pkg/kubernetes.test imports
	k8s.io/kubernetes/pkg/client/clientset_generated/clientset/fake: cannot find module providing package k8s.io/kubernetes/pkg/client/clientset_generated/clientset/fake
fejta@erick:~/kubernetes$
```

**Comment by liggitt** [comment]
there's a fair number of build/releng issues we'll have to deal with for 1.13

xref https://github.com/kubernetes/kubernetes/issues/78845

**Comment by liggitt** [comment]
looks like `go mod tidy` in go1.13 might now require all transitively referenced packages in dependencies to resolve, even ones we don't actually depend on in our tree (go1.12 did not require that, so because we didn't actually depend on any of the heketi packages that used the old client-go, we weren't affected by its outdated client-go dependency).

that means the [outdated k8s.io/client-go library](https://github.com/heketi/heketi/blob/v9.0.0/glide.yaml#L23-L24) the current version of the heketi dependency uses will not work properly

xref https://github.com/heketi/heketi/pull/1542

**Comment by zouyee** [comment]
```
GO111MODULE=off GOOGLE_APPLICATION_CREDENTIALS=./kubernetes-8d07a080f91f.json make test-e2e-node PARALLELISM=1 REMOTE=true FOCUS="CriticalPod" SKIP=""
+++ [0910 09:45:36] Building go targets for linux/amd64:
    vendor/github.com/onsi/ginkgo/ginkgo
go/build: importGo k8s.io/kubernetes: exit status 1
can't load package: package k8s.io/kubernetes: cannot find module providing package k8s.io/kubernetes
```
