### PR TITLE
Allow kubectl describe ns to pass if server does not support resource quotas and limit ranges

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/32629

Context: federation-apiserver does not support limit ranges and resource quotas. Hence `kubectl describe ns` fails right now.
Fixing it so that `kubectl describe ns` does not error out and atleast prints information about the namespace.

cc @kubernetes/sig-cluster-federation @kubernetes/kubectl

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32823)

### CODE REVIEW

File: pkg/kubectl/describe.go [hunk 1]
```diff
@@ -173,13 +173,24 @@ func (d *NamespaceDescriber) Describe(namespace, name string, describerSettings
 	}
 	resourceQuotaList, err := d.Core().ResourceQuotas(name).List(api.ListOptions{})
 	if err != nil {
-		return "", err
+		if errors.IsNotFound(err) {
+			// Server does not support resource quotas.
+			// Not an error, will not show resource quotas information.
+			resourceQuotaList = nil
+		} else {
+			return "", err
```
Comment (quinton-hoole) [inline pkg/kubectl/describe.go]: Do we not want to return a result, with error placeholders for the missing data?

**Comment by quinton-hoole** [comment]
@nikhiljindal Looks good barring the nit.  What do you think?

File: pkg/kubectl/describe.go (hunk 1 above)
Comment (nikhiljindal) [inline pkg/kubectl/describe.go]: Yes thats a good point. However doing that will require some refactoring.
I will need to update describeNamespace to take errors for both resourceQuota and limit ranges and then update describeResourceQuota and describeLimitRanges to take errors as well.
Or I could directly pass the output of describeLimitRanges and describeResourceQuotas to describeNamespace.
But I decided not to make those changes in this PR, since that case is not critical for us.

Let me know if you want me to include that in this PR.

Comment (smarterclayton) [inline pkg/kubectl/describe.go]: This is fine and mimics what we do in a few other places.  Please open a follow up issue for 1.5 though - we have other cases that probably need to be unified here.

File: pkg/kubectl/describe.go [hunk 2]
```diff
@@ -173,13 +173,24 @@ func (d *NamespaceDescriber) Describe(namespace, name string, describerSettings
 	}
 	resourceQuotaList, err := d.Core().ResourceQuotas(name).List(api.ListOptions{})
 	if err != nil {
-		return "", err
+		if errors.IsNotFound(err) {
```
Comment (deads2k) [inline pkg/kubectl/describe.go]: Why are 404's special? Seems like I'd want a best effort describe regardless of why my request failed.

**Comment by deads2k** [comment]
I second the request for an issue and have a question about why 404s are special.

File: pkg/kubectl/describe.go (hunk 2 above)
Comment (nikhiljindal) [inline pkg/kubectl/describe.go]: I wanted to put a very specific fix to minimize the risk of getting this cherrypicked in 1.4.
I will prefer doing a generic fix in another PR, unless you really really want me to do it in this PR.

**Comment by nikhiljindal** [comment]
Filed https://github.com/kubernetes/kubernetes/issues/32883

File: pkg/kubectl/describe.go (hunk 2 above)
Comment (nikhiljindal) [inline pkg/kubectl/describe.go]: I meant specific fix for https://github.com/kubernetes/kubernetes/issues/32629

**Comment by deads2k** [comment]
> I meant specific fix for #32629

ok

**Comment by nikhiljindal** [comment]
Changing milestone from 1.4-non-blocking to 1.4 to allow cherrypicking

**Comment by quinton-hoole** [comment]
GCE Node e2e test failure looks like a flake:

`SUCCESS! -- 97 Passed | 0 Failed | 0 Pending | 35 Skipped `

@k8s-bot test this ISSUE #IGNORE

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by pwittrock** [comment]
@deads2k @nikhiljindal FYI, this cherrypick does not compile on the 1.4 branch with the following error:

>
ok  	k8s.io/kubernetes/# k8s.io/kubernetes/pkg/kubectl
pkg/kubectl/describe_test.go:95: cannot use fake (type *"k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/fake".Clientset) as type "k8s.io/kubernetes/pkg/client/unversioned".Interface in field value:
	*"k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/fake".Clientset does not implement "k8s.io/kubernetes/pkg/client/unversioned".Interface (missing Apps method)

**Comment by nikhiljindal** [comment]
I cant see how this PR can result in that error.
Trying a manual cherrypick to see whats the issue

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/33042 that does manual cherrypick
