### ISSUE TITLE
Compile issue - generated.Asset[Names] undefined

### ISSUE THREAD

**Issue by gavinB-orange** [kubernetes/kubernetes#33825]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

generated.Asset

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug Report

**Kubernetes version** (use `kubectl version`):

Today's HOT.

commit b71def750f3ec1978b0e890e6fae106a20f33a9b

**Environment**:

Build on Ubuntu 16.04

**What happened**:

git pull of latest code, then make release fails with

```
+++ [0930 02:04:05] Starting etcd instance
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /tmp.k8s/tmp.fcfyJnEiqq --listen-client-urls http://127.0.0.1:2379 --debug > "/dev/null" 2>/dev/null
Waiting for etcd to come up.
+++ [0930 02:04:05] On try 1, etcd: :
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [0930 02:04:06] Running integration test cases
Running tests for APIVersion: v1,apps/v1alpha1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1beta1,autoscaling/v1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1alpha1,
extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1alpha1,rbac.authorization.k8s.io/v1alpha1,storage.k8s.io/v1beta1
+++ [0930 02:04:07] Running tests without code coverage
# k8s.io/kubernetes/test/e2e/framework
test/e2e/framework/gobindata_util.go:30: undefined: generated.Asset
test/e2e/framework/gobindata_util.go:33: undefined: generated.AssetNames
Makefile:118: recipe for target 'test' failed
make[1]: *** [test] Error 1
+++ [0930 02:05:19] Cleaning up etcd
+++ [0930 02:05:19] Integration test cleanup complete
Makefile:130: recipe for target 'test-integration' failed
make: *** [test-integration] Error 1
Makefile:239: recipe for target 'release' failed
make: *** [release] Error 1

```

**What you expected to happen**:

Build to complete

**How to reproduce it** (as minimally and precisely as possible):

git pull; make release

**Anything else do we need to know**:

I saw the same thing yesterday on a slightly older commit, so this is not a very recent regression.

**Comment by dims** [comment]
@gavinB-orange - Are you git cloning under `$GOPATH/src/k8s.io` (per https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#clone-your-fork)?

**Comment by gavinB-orange** [comment]
No I'm not. I was following the instructions at http://kubernetes.io/docs/getting-started-guides/binary_release/ which say:

```
Get the Kubernetes source. If you are simply building a release from source there is no need to set up a full golang environment as all building happens in a Docker container.
Building a release is simple.
git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
make release
```

Sounds like this may not be correct.

**Comment by gavinB-orange** [comment]
Same issue if you follow the instructions on https://github.com/kubernetes/kubernetes/blob/a698d490b93a4829d9af76bed7556a446eef7238/build/README.md


build/run.sh make test-integration fails with this error.

**Comment by pbx0** [comment]
I have run into the same problem myself. Containerized builds seem to not be setting up the GOPATH correctly. I get this error in non-containerized builds if I don't create my GOPATH properly, but in containerized builds we don't have easy control of how the GOPATH is setup in the container so it doesn't matter how it was cloned originally.

**Comment by kiall** [comment]
Yep, happens on all container builds:

	$ ./build-tools/run.sh make test-integration

	.... SNIP

	+++ [1103 10:57:42] Running integration test cases
	Running tests for APIVersion: v1,apps/v1alpha1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1beta1,autoscaling/v1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1alpha1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1alpha1,rbac.authorization.k8s.io/v1alpha1,storage.k8s.io/v1beta1
	+++ [1103 10:57:46] Running tests without code coverage
	# k8s.io/kubernetes/test/e2e/framework
	test/e2e/framework/gobindata_util.go:30: undefined: generated.Asset
	test/e2e/framework/gobindata_util.go:33: undefined: generated.AssetNames
	Makefile:118: recipe for target 'test' failed
	make[1]: *** [test] Error 1
	+++ [1103 10:57:50] Cleaning up etcd
	+++ [1103 10:57:50] Integration test cleanup complete
	Makefile:130: recipe for target 'test-integration' failed
	make: *** [test-integration] Error 1
	!!! Error in ./build-tools/../build-tools/common.sh:587
	  '"${docker_cmd[@]}" "${cmd[@]}"' exited with status 2
	Call stack:
	  1: ./build-tools/../build-tools/common.sh:587 kube::build::run_build_command_ex(...)
	  2: ./build-tools/../build-tools/common.sh:522 kube::build::run_build_command(...)
	  3: ./build-tools/run.sh:30 main(...)
	Exiting with status 1

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.

**Comment by louisgriffin** [comment]
still regrettable with latest kubernetes:
```
+++ [0207 15:45:06] Starting etcd instance^M                                                                                 
85070 etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /tmp.k8s/tmp.HKw3OyCC8p --listen-client-urls http://127.0.0.1:2      379 --debug > "/dev/null" 2>/dev/null^M                                                                                      
85071 Waiting for etcd to come up.^M                                                                                               
85072 +++ [0207 15:45:06] On try 2, etcd: : http://127.0.0.1:2379^M                                                                
85073 {"action":"set","node":{"key":"/_test","value":"","modifiedIndex":4,"createdIndex":4}}^M                                     
85074 +++ [0207 15:45:06] Running integration test cases^M                                                                         
85075 Running tests for APIVersion: v1,admissionregistration.k8s.io/v1alpha1,admissionregistration.k8s.io/v1beta1,admission.k8s.io/      v1beta1,apps/v1beta1,apps/v1beta2,apps/v1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,auth      orization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2beta1,batch/v1,batch/v1beta1,batch/v2alpha1,certificates.k8s.io/v1beta1      ,extensions/v1beta1,events.k8s.io/v1beta1,imagepolicy.k8s.io/v1alpha1,networking.k8s.io/v1,policy/v1beta1,rbac.authorization.      k8s.io/v1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,scheduling.k8s.io/v1alpha1,settings.k8s.io/v1a      lpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,storage.k8s.io/v1alpha1,^M                                                    
85076 +++ [0207 15:45:12] Running tests without code coverage^M                                                                    
85077 # k8s.io/kubernetes/test/e2e/generated^M                                                                                     
85078 test/e2e/generated/gobindata_util.go:29:20: undefined: Asset^M                                                               
85079 test/e2e/generated/gobindata_util.go:32:48: undefined: AssetNames^M                                                          
85080 !!! [0207 15:47:28] Call tree:^M                                                                                             
85081 !!! [0207 15:47:28]  1: hack/make-rules/test.sh:402 runTests(...)^M                                                          
85082 !!! Error in hack/make-rules/test.sh:284^M                                                                                   
85083   Error in hack/make-rules/test.sh:284. '((i<3-1))' exited with status 2^M                                                   
85084 Call stack:^M                                                                                                                
85085   1: hack/make-rules/test.sh:284 runTests(...)^M                                                                             
85086   2: hack/make-rules/test.sh:402 main(...)^M                                                                                 
85087 Exiting with status 1^M                                                                                                      
85088 Makefile:182: recipe for target 'test' failed^M                                                                              
85089 make[1]: *** [test] Error 1^M                                                                                                
85090 !!! [0207 15:47:28] Call tree:^M                                                                                             
85091 !!! [0207 15:47:28]  1: hack/make-rules/test-integration.sh:105 runTests(...)^M                                              
85092 !!! Error in hack/make-rules/test-integration.sh:71^M                                                                        
85093   Error in hack/make-rules/test-integration.sh:71. '((i<3-1))' exited with status 2^M                                        
85094 Call stack:^M                                                                                                                
85095   1: hack/make-rules/test-integration.sh:71 runTests(...)^M                                                                  
85096   2: hack/make-rules/test-integration.sh:105 main(...)^M                                                                     
85097 Exiting with status 1^M                                                                                                      
85098 +++ [0207 15:47:28] Cleaning up etcd^M                                                                                       
85099 +++ [0207 15:47:28] Integration test cleanup complete^M                                                                      
85100 Makefile:201: recipe for target 'test-integration' failed^M                                                                  
85101 make: *** [test-integration] Error 1^M                                                                                       
85102 !!! [0207 15:47:27] Call tree:                                                                                               
85103 !!! [0207 15:47:28]  1: build/../build/common.sh:551 kube::build::run_build_command_ex(...)                                  
85104 !!! [0207 15:47:28]  2: build/run.sh:39 kube::build::run_build_command(...)                                                  
85105 !!! Error in build/../build/common.sh:559                                                                                    
85106   Error in build/../build/common.sh:559. '((i<4-1))' exited with status 2                                                    
85107 Call stack:                                                                                                                  
85108   1: build/../build/common.sh:559 kube::build::run_build_command_ex(...)                                                     
85109   2: build/../build/common.sh:551 kube::build::run_build_command(...)                                                        
85110   3: build/run.sh:39 main(...)                                                                                               
85111 Exiting with status 1      
```
