### ISSUE TITLE
client-go: FakeCustomStore no longer implements cache.Store after #134827

### ISSUE THREAD

**Issue by alancaldelas** [kubernetes/kubernetes#140965]
### What happened?

#134827 (merged 2025-10-23, shipped in client-go v0.36) added two methods to the `cache.Store` interface:

- `Bookmark(rv string)`
- `LastStoreSyncResourceVersion() string`

The package's own test double `cache.FakeCustomStore` (`staging/src/k8s.io/client-go/tools/cache/fake_custom_store.go`) was not updated, so it no longer satisfies `cache.Store`. Downstream test code that passes a `FakeCustomStore` where a `Store` is expected now fails to compile:

```
cannot use &cache.FakeCustomStore{...} (value of type *cache.FakeCustomStore) as cache.Store value:
	*cache.FakeCustomStore does not implement cache.Store (missing method Bookmark)
```

We hit this in the wild during KubeVirt's bump to v0.36.2 (kubevirt/kubevirt#18315) and had to add a local wrapper to keep ~10 test files compiling.

### What did you expect to happen?

`FakeCustomStore` keeps satisfying `cache.Store`. It is named and documented as a general store fake ("lets you define custom functions for store operations") and has satisfied `Store` since 2016. The new narrower `ReflectorStore` interface is not a substitute for read-path consumers (it has no `List`/`GetByKey`), and #134827 carried no deprecation signal for the fake.

### How can we reproduce it (as minimally and precisely as possible)?

```go
package main

import "k8s.io/client-go/tools/cache"

var _ cache.Store = &cache.FakeCustomStore{} // fails to compile with client-go v0.36.x
```

### Anything else we need to know?

Proposed fix (~15 lines, backward compatible): add `BookmarkFunc func(rv string)` and `LastStoreSyncResourceVersionFunc func() string` fields plus the two delegating methods (no-op / `""` when nil), matching the file's existing pattern. Happy to submit the PR.

### Kubernetes version

client-go v0.36.x (still present on master as of 2026-07-27)

/sig api-machinery
/kind bug
