### ISSUE TITLE
AWS kube-up: fails to create /srv/kubernetes/abac-authz-policy.jsonl

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#29424]
```
2016-07-22 04:02:42,496 [salt.state       ][INFO    ] Running state [/srv/kubernetes/abac-authz-policy.jsonl] at time 04:02:42.495534
2016-07-22 04:02:42,496 [salt.state       ][INFO    ] Executing state file.managed for /srv/kubernetes/abac-authz-policy.jsonl
2016-07-22 04:02:42,502 [salt.state       ][ERROR   ] Unable to manage file: Jinja variable 'dict object' has no attribute 'kube_user'; line 3

---
{% set kube_user = grains.kube_user -%}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"admin", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"{{kube_user}}", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}}    <======================
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"kubelet", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"kube_proxy", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"kubecfg", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"client", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"group":"system:serviceaccounts", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}}
---
```

**Comment by justinsb** [comment]
Looks like this was broken by #29164 (which means no cherry pick).  Fix incoming...
