### PR TITLE
Implement GetCapacity in container_manager_unsupported

### LINKED ISSUE #48234: Cross build failed in unsupportedContainerManager
```
I0628 18:33:54.041] # k8s.io/kubernetes/pkg/kubelet/cm
I0628 18:33:54.041] pkg/kubelet/cm/container_manager_unsupported.go:33: cannot use unsupportedContainerManager literal (type *unsupportedContainerManager) as type ContainerManager in assignment:
I0628 18:33:54.042] 	*unsupportedContainerManager does not implement ContainerManager (missing GetCapacity method)
I0628 18:33:54.042] pkg/kubelet/cm/container_manager_unsupported.go:72: cannot use unsupportedContainerManager literal (type *unsupportedContainerManager) as type ContainerManager in return argument:
I0628 18:33:54.042] 	*unsupportedContainerManager does not implement ContainerManager (missing GetCapacity method)
```
It was introduced by https://github.com/kubernetes/kubernetes/pull/48123/files

cc/ @msau42

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48234

**Special notes for your reviewer**:
/cc @dchen1107 @caesarxuchao 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dchen1107** [comment]
/lgtm

Thanks for quickly pr to fix the broken builds!

**Comment by xiangpengzhao** [comment]
Team work for the release:)

**Comment by dchen1107** [comment]
I am manually merging this to stop the crossing-build failures.

@kubernetes/kubernetes-release-managers
