### PR TITLE
Automated cherry pick of #37328

### PR DESCRIPTION
**Pull request by zhouhaibing089**
Cherry pick of #37328 on release-1.5.

#37328: make thirdparty codec able to decode DeleteOptions

### CODE REVIEW

**Comment by saad-ali** [comment]
@k8s-bot ok to test

**Comment by saad-ali** [comment]
This is a bad merge, causing the build to fail, which is why the E2Es are failing:

```
W0110 14:17:22.789] test/e2e/third-party.go:166: undefined: v1 in v1.NewDeleteOptions
```

**Comment by zhouhaibing089** [comment]
@saad-ali I am gonna to fix it.

**Comment by zhouhaibing089** [comment]
@saad-ali I've updated the code, with the fix to add the import of `k8s.io/kubernetes/pkg/api/v1`.
