### ISSUE TITLE
unable to 'make' in kubernetes build with go version 1.13

### ISSUE THREAD

**Issue by kylix3511** [kubernetes/kubernetes#83124]
**What happened**:

``` 
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io/kubernetes  git:(release-1.16.0) make
go/build: importGo k8s.io/kubernetes: exit status 1
can't load package: package k8s.io/kubernetes: cannot find module providing package k8s.io/kubernetes


+++ [0925 10:12:16] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
go: finding k8s.io/kubernetes/vendor latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen latest
go: finding k8s.io/kubernetes/vendor/k8s.io latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd latest
can't load package: package k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen: no matching versions for query "latest"
!!! [0925 10:12:23] Call tree:
!!! [0925 10:12:23]  1: /Users/rameshkumar/go/k8s.io/kubernetes/hack/lib/golang.sh:714 kube::golang::build_some_binaries(...)
!!! [0925 10:12:23]  2: /Users/rameshkumar/go/k8s.io/kubernetes/hack/lib/golang.sh:853 kube::golang::build_binaries_for_platform(...)
!!! [0925 10:12:23]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0925 10:12:23] Call tree:
!!! [0925 10:12:23]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0925 10:12:23] Call tree:
!!! [0925 10:12:23]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io/kubernetes  git:(release-1.16.0) 
``` 
**What you expected to happen**:
Build should working 

**How to reproduce it (as minimally and precisely as possible)**:
```
(☸ |kind@local.k8s:default)➜  ☸️  ~/go  mkdir k8s.io
(☸ |kind@local.k8s:default)➜  ☸️  ~/go  cd k8s.io
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io  git clone -v https://github.com/kubernetes/kubernetes
Cloning into 'kubernetes'...
POST git-upload-pack (gzip 30115 to 15199 bytes)
remote: Enumerating objects: 255, done.
remote: Counting objects: 100% (255/255), done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 1008508 (delta 140), reused 123 (delta 123), pack-reused 1008253
Receiving objects: 100% (1008508/1008508), 670.20 MiB | 905.00 KiB/s, done.
Resolving deltas: 100% (708834/708834), done.
Updating files: 100% (20992/20992), done.
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io  ls -ler
total 0
drwxr-xr-x  55 rameshkumar  staff  1760 Sep 25 10:06 kubernetes
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io  cd kubernetes
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io/kubernetes  git:(master) make
go: downloading github.com/spf13/pflag v1.0.3
go: extracting github.com/spf13/pflag v1.0.3
go: finding github.com/spf13/pflag v1.0.3
go/build: importGo k8s.io/kubernetes: exit status 1
can't load package: package k8s.io/kubernetes: cannot find module providing package k8s.io/kubernetes


+++ [0925 10:07:14] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd latest
go: finding k8s.io/kubernetes/vendor/k8s.io latest
go: finding k8s.io/kubernetes/vendor latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator latest
can't load package: package k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen: no matching versions for query "latest"
!!! [0925 10:08:11] Call tree:
!!! [0925 10:08:11]  1: /Users/rameshkumar/go/k8s.io/kubernetes/hack/lib/golang.sh:714 kube::golang::build_some_binaries(...)
!!! [0925 10:08:11]  2: /Users/rameshkumar/go/k8s.io/kubernetes/hack/lib/golang.sh:853 kube::golang::build_binaries_for_platform(...)
!!! [0925 10:08:11]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0925 10:08:11] Call tree:
!!! [0925 10:08:11]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0925 10:08:11] Call tree:
!!! [0925 10:08:11]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io/kubernetes  git:(master)

``` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io/kubernetes  git:(release-1.16.0) kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server 127.0.0.1:54861 was refused - did you specify the right host or port?
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io/kubernetes  git:(release-1.16.0)
```
- Cloud provider or hardware configuration: 
Local MacOS 
- OS (e.g: `cat /etc/os-release`):

- Kernel (e.g. `uname -a`):

``` 
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io/kubernetes  git:(release-1.16.0) uname -a
Darwin Ramesh-MacBook.local 19.0.0 Darwin Kernel Version 19.0.0: Tue Aug  6 20:16:30 PDT 2019; root:xnu-6153.0.139.161.1~1/RELEASE_X86_64 x86_64
(☸ |kind@local.k8s:default)➜  ☸️  ~/go/k8s.io/kubernetes  git:(release-1.16.0)

``` 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tpepper** [comment]
/sig contributor-experience

We should add `go version` to the bug report template.

**Comment by tpepper** [comment]
I suspect this is the difference between building right now with go version 1.12.9 and 1.13.

**Comment by liggitt** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/78845

Support for go1.13 is being tracked in #82531

/close
