### PR TITLE
Validate kube-proxy options

### LINKED ISSUE #53852: Should validate ipvs proxy options
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Some kube-proxy options are not validated.

**What you expected to happen**:

We should validate these options before running.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network

/area kube-proxy

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

Validate ipvs proxy options

**Which issue this PR fixes** : fixes #53852

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/apis/componentconfig/types.go [hunk 1]
```diff
@@ -149,15 +149,16 @@ type KubeProxyConfiguration struct {
...
+// (newer, faster), or 'ipvs'(experimental). If blank, use the best-available proxy (currently iptables,
+// but may change in future versions).  If the iptables proxy is selected, regardless of how, but
 // the system's kernel or iptables versions are insufficient, this always falls back to the
 // userspace proxy.
 type ProxyMode string
 
 const (
 	ProxyModeUserspace ProxyMode = "userspace"
 	ProxyModeIPTables  ProxyMode = "iptables"
+	ProxyModeIPVS      ProxyMode = "ipvs"
```
Comment (frodenas) [inline pkg/apis/componentconfig/types.go]: For your reference, #53860 also add IPVS and Kernelspace.

Comment (m1093782566) [reply pkg/apis/componentconfig/types.go]: Thanks!

**Comment by xiangpengzhao** [comment]
@m1093782566 so sorry for not noticing this PR when I trying to improve test coverage for kube-proxy validation in #54848. For the IPVS part, this PR is more reasonable than that one.

**Comment by m1093782566** [comment]
@xiangpengzhao 

Never mind. I think you did good job :)

File: cmd/kube-proxy/app/validation_test.go [hunk 2]
```diff
@@ -279,6 +307,133 @@ func TestValidateKubeProxyIPTablesConfiguration(t *testing.T) {
...
+		if len(errs) == 0 && test.expectErr {
+			t.Errorf("Expect error, got nil, reason: %s", test.reason)
+		}
+		if len(errs) > 0 && !test.expectErr {
+			t.Errorf("Unexpected error: %v", errs)
+		}
+	}
+}
+
+func TestValidateKubeProxyIPVSScheduler(t *testing.T) {
```
Comment (xiangpengzhao) [inline cmd/kube-proxy/app/validation_test.go]: This test case can be removed here since it's already added in  #54848 :)

File: cmd/kube-proxy/app/validation.go [hunk 3]
```diff
@@ -90,6 +90,22 @@ func validateKubeProxyIPTablesConfiguration(config componentconfig.KubeProxyIPTa
...
 }
 
+func validateKubeProxyIPVSConfiguration(config componentconfig.KubeProxyIPVSConfiguration, fldPath *field.Path) field.ErrorList {
+	allErrs := field.ErrorList{}
+
+	if config.SyncPeriod.Duration <= 0 {
+		allErrs = append(allErrs, field.Invalid(fldPath.Child("SyncPeriod"), config.SyncPeriod, "must be greater than 0"))
+	}
+
+	if config.MinSyncPeriod.Duration < 0 {
```
Comment (xiangpengzhao) [inline cmd/kube-proxy/app/validation.go]: Do we need to check if MinSyncPeriod > SyncPeriod ?

**Review by xiangpengzhao — COMMENTED** [review]
just two nits. otherwise LGTM.

File: cmd/kube-proxy/app/validation.go (hunk 3 above)
Comment (m1093782566) [reply cmd/kube-proxy/app/validation.go]: That's a nice finding! 

I think we can check `MinSyncPeriod > SyncPeriod` in validation although currently it's already checked in proxier.go. Let's change it to see if anyone object to it :)

File: cmd/kube-proxy/app/validation_test.go (hunk 2 above)
Comment (m1093782566) [reply cmd/kube-proxy/app/validation_test.go]: No problem.

File: cmd/kube-proxy/app/validation.go (hunk 3 above)
Comment (xiangpengzhao) [reply cmd/kube-proxy/app/validation.go]: >although currently it's already checked in proxier.go

IMO, it's better validating earlier than later :)

**Comment by m1093782566** [comment]
@xiangpengzhao 

Comments are fixed now, PTAL. Thanks!

File: cmd/kube-proxy/app/validation.go [hunk 4]
```diff
@@ -87,6 +87,30 @@ func validateKubeProxyIPTablesConfiguration(config componentconfig.KubeProxyIPTa
 		allErrs = append(allErrs, field.Invalid(fldPath.Child("MinSyncPeriod"), config.MinSyncPeriod, "must be greater than or equal to 0"))
 	}
 
+	if config.MinSyncPeriod.Duration > config.SyncPeriod.Duration {
```
Comment (xiangpengzhao) [inline cmd/kube-proxy/app/validation.go]: why checking this both here and L108?

Comment (m1093782566) [reply cmd/kube-proxy/app/validation.go]: That's an interesting finding :)

Because both iptables and ipvs proxy has the `SyncPeriod` and `MinSyncPeriod` - they don't share the same `SyncPeriod` and `MinSyncPeriod`.

Comment (m1093782566) [reply cmd/kube-proxy/app/validation.go]: We need to validate them both in iptables and ipvs mode.

Comment (xiangpengzhao) [reply cmd/kube-proxy/app/validation.go]: Cool! I didn't notice this :)

File: pkg/apis/componentconfig/types.go [hunk 5]
```diff
@@ -20,6 +20,191 @@ import (
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
+// ClientConnectionConfiguration contains details for constructing a client.
```
Comment (xiangpengzhao) [inline pkg/apis/componentconfig/types.go]: These should be removed from this file as #53645 is merged.

File: pkg/proxy/apis/kubeproxyconfig/types.go [hunk 6]
```diff
@@ -163,6 +163,7 @@ const (
 	ProxyModeUserspace ProxyMode = "userspace"
 	ProxyModeIPTables  ProxyMode = "iptables"
 	ProxyModeIPVS      ProxyMode = "ipvs"
+	ProxyModeIPVS      ProxyMode = "ipvs"
```
Comment (xiangpengzhao) [inline pkg/proxy/apis/kubeproxyconfig/types.go]: dup of L165

**Review by xiangpengzhao — CHANGES_REQUESTED** [review]
please fix the dup code caused by rebase.

File: pkg/apis/componentconfig/types.go (hunk 5 above)
Comment (m1093782566) [reply pkg/apis/componentconfig/types.go]: Fixed. Thanks!

File: pkg/proxy/apis/kubeproxyconfig/types.go (hunk 6 above)
Comment (m1093782566) [reply pkg/proxy/apis/kubeproxyconfig/types.go]: nice catch! Done.

**Comment by xiangpengzhao** [comment]
CI is still unhappy due to 
```
I1107 09:23:00.377] pkg/proxy/apis/kubeproxyconfig/validation/validation.go:97:48: undefined: componentconfig
I1107 09:23:00.378] pkg/proxy/apis/kubeproxyconfig/validation/validation.go:112:56: undefined: componentconfig
```

I guess this is also introduced by rebase. Sorry for the pain caused by #53645. It hurts a lot of PRs.

File: pkg/proxy/apis/kubeproxyconfig/validation/validation.go [hunk 7]
```diff
@@ -87,6 +87,30 @@ func validateKubeProxyIPTablesConfiguration(config kubeproxyconfig.KubeProxyIPTa
...
 	}
 
+	if config.MinSyncPeriod.Duration > config.SyncPeriod.Duration {
+		allErrs = append(allErrs, field.Invalid(fldPath.Child("SyncPeriod"), config.MinSyncPeriod, fmt.Sprintf("must be greater than or equal to %s", fldPath.Child("MinSyncPeriod").String())))
+	}
+
+	return allErrs
+}
+
+func validateKubeProxyIPVSConfiguration(config componentconfig.KubeProxyIPVSConfiguration, fldPath *field.Path) field.ErrorList {
```
Comment (xiangpengzhao) [inline pkg/proxy/apis/kubeproxyconfig/validation/validation.go]: s/componentconfig/kubeproxyconfig
and other places it appears.

**Review by xiangpengzhao — COMMENTED** [review]
just a nit now.

File: pkg/proxy/apis/kubeproxyconfig/validation/validation.go (hunk 7 above)
Comment (m1093782566) [reply pkg/proxy/apis/kubeproxyconfig/validation/validation.go]: sure.

**Comment by m1093782566** [comment]
CI is happy now :)
