### ISSUE TITLE
Cross build failed in unsupportedContainerManager

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#48234]
```
I0628 18:33:54.041] # k8s.io/kubernetes/pkg/kubelet/cm
I0628 18:33:54.041] pkg/kubelet/cm/container_manager_unsupported.go:33: cannot use unsupportedContainerManager literal (type *unsupportedContainerManager) as type ContainerManager in assignment:
I0628 18:33:54.042] 	*unsupportedContainerManager does not implement ContainerManager (missing GetCapacity method)
I0628 18:33:54.042] pkg/kubelet/cm/container_manager_unsupported.go:72: cannot use unsupportedContainerManager literal (type *unsupportedContainerManager) as type ContainerManager in return argument:
I0628 18:33:54.042] 	*unsupportedContainerManager does not implement ContainerManager (missing GetCapacity method)
```
It was introduced by https://github.com/kubernetes/kubernetes/pull/48123/files

cc/ @msau42

**Comment by dchen1107** [comment]
cc/ @kubernetes/kubernetes-release-managers

**Comment by msau42** [comment]
Only in 1.7 or also 1.8?

**Comment by xiangpengzhao** [comment]
PR #48235 sent.
