### PR TITLE
Refactor test to use new fake reactors

### PR DESCRIPTION
**Pull request by ironcladlou**
Fix a test compilation error by refactoring the test code to use
the latest fake reactor framework.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Fixes a breakage introduced by #11942

**Comment by ironcladlou** [comment]
Related to #13499

**Comment by smarterclayton** [comment]
LGTM
