### PR TITLE
WIP: client-go cache: restore SharedInformer interface from <= 1.35

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Introducing DoneChecker changed the SharedInformer interface to keep the client-go code simpler, assuming that the impact on the ecosystem would be low because sharedIndexInformer look like the main implementation of this interface.

It was later called out that there this is a bigger breaking change than expected because there are other SharedInformer implementations. Therefore this change reverts to the original interface definition and instead uses type assertion to get access to sharedIndexInformer.HasSyncedChecker.

#### Which issue(s) this PR is related to:

Follow-up to https://github.com/kubernetes/kubernetes/pull/135395

/cc @sbueringer @aojea @alvaroaleman @michaelasp @jpbetz 

#### Special notes for your reviewer:

Out-of-tree SharedInformer implementations are supported by the SharedInformerFactory implementations by polling their mandatory HasSynced method, using some wrapper provided by client-go.

This approach keeps WaitFor and SharedInformerFactory type-safe. The alternative would have been a `WaitFor(..., checker any)` where the informer or DoneChecker instances get passed and then `WaitFor` figures out how to check. This seems worse than the current solution with DoneCheckerForInformer.

WIP because I want to get feedback on the proposal before adding unit tests.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: staging/src/k8s.io/client-go/tools/cache/shared_informer.go [hunk 1]
```diff
@@ -248,6 +240,74 @@ type SharedInformer interface {
...
 }
 
+// ^^^
+// SharedInformer *is* implemented widely out-of-tree and therefore has to
+// be considered frozen for practical reasons. Consider using an approach as with
+// HasSyncedChecker below instead of adding methods.
+
+// HasSyncedChecker defines an additional method that SharedInformer implementations
+// may provide to support waiting for cache sync without polling. All SharedInformer
+// instances created by client-go itself implement this interface.
```
Comment (pohly) [inline staging/src/k8s.io/client-go/tools/cache/shared_informer.go:250]: This guarantee simplifies code which calls e.g. `Informer()` from the typed client-go: it makes `podInformer.Informer().(cache.HasSyncChecker).HasSyncedChecker()` valid despite the unchecked type assertion.

Authors who want to play it safe can use `DoneCheckerForInformer`, but then need a context.

File: staging/src/k8s.io/client-go/tools/cache/shared_informer.go [hunk 2]
```diff
@@ -197,14 +197,6 @@ type SharedInformer interface {
...
 	// AddEventHandler.
 	HasSynced() bool
-	// HasSyncedChecker completes if the shared informer's store has been
-	// informed by at least one full LIST of the authoritative state
-	// of the informer's object collection.  This is unrelated to "resync".
-	//
-	// Note that this doesn't tell you if an individual handler is synced!!
-	// For that, please use HasSyncedChecker on the handle returned by
-	// AddEventHandler.
-	HasSyncedChecker() DoneChecker
```
Comment (pohly) [inline staging/src/k8s.io/client-go/tools/cache/shared_informer.go:207]: With this removal, current master has the following incompatible API changes in client-go:

```console
$ hack/apidiff.sh -r v1.35.0 -t HEAD ./staging/src/k8s.io/client-go
Checking e7051a53a633669c6e87b03ae6adf661f2129d78 (= v1.36.0-alpha.1-220-ge7051a53a63) for API changes since 2049416c7235eeec9a413c38472708e49af3ed88 (= v1.35.0).
Installing apidiff into /tmp/tmp.aRrAKMG2zc.
go: downloading golang.org/x/exp v0.0.0-20260212183809-81e46e3db34a
go: downloading golang.org/x/tools v0.42.0
go: downloading golang.org/x/mod v0.33.0
Preparing worktree (detached HEAD e7051a53a63)
Updating files: 100% (28333/28333), done.
HEAD is now at e7051a53a63 client-go cache: restore SharedInformerCache interface from <= 1.35
Preparing worktree (detached HEAD 66452049f3d)
Updating files: 100% (28352/28352), done.
HEAD is now at 66452049f3d Release commit for Kubernetes v1.35.0

## ./staging/src/k8s.io/client-go
! second, different message for obj type k8s.io/client-go/tools/cache.SharedInformer interface{AddEventHandler(handler k8s.io/client-go/tools/cache.ResourceEventHandler) (k8s.io/client-go/tools/cache.ResourceEventHandlerRegistration, error); AddEventHandlerWithOptions(handler k8s.io/client-go/tools/cache.ResourceEventHandler, options k8s.io/client-go/tools/cache.HandlerOptions) (k8s.io/client-go/tools/cache.ResourceEventHandlerRegistration, error); AddEventHandlerWithResyncPeriod(handler k8s.io/client-go/tools/cache.ResourceEventHandler, resyncPeriod time.Duration) (k8s.io/client-go/tools/cache.ResourceEventHandlerRegistration, error); GetController() k8s.io/client-go/tools/cache.Controller; GetStore() k8s.io/client-go/tools/cache.Store; HasSynced() bool; IsStopped() bool; LastSyncResourceVersion() string; RemoveEventHandler(handle k8s.io/client-go/tools/cache.ResourceEventHandlerRegistration) error; Run(stopCh <-chan struct{}); RunWithContext(ctx context.Context); SetTransform(handler k8s.io/client-go/tools/cache.TransformFunc) error; SetWatchErrorHandler(handler k8s.io/client-go/tools/cache.WatchErrorHandler) error; SetWatchErrorHandlerWithContext(handler k8s.io/client-go/tools/cache.WatchErrorHandlerWithContext) error}, isNew false, part ""
  first:  no longer implements ./tools/cache.Controller
  second: no longer implements ./tools/cache.ResourceEventHandlerRegistration
! second, different message for obj type k8s.io/client-go/tools/cache.SharedIndexInformer interface{AddIndexers(indexers k8s.io/client-go/tools/cache.Indexers) error; GetIndexer() k8s.io/client-go/tools/cache.Indexer; k8s.io/client-go/tools/cache.SharedInformer}, isNew false, part ""
  first:  no longer implements ./tools/cache.Controller
  second: no longer implements ./tools/cache.ResourceEventHandlerRegistration
Incompatible changes:
- ./informers.SharedInformerFactory.StartWithContext: added
- ./informers.SharedInformerFactory.WaitForCacheSyncWithContext: added
- ./informers/internalinterfaces.SharedInformerFactory.InformerName: added
- ./informers/internalinterfaces.SharedInformerFactory.InformerName: added
- package k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2/fake: removed
- package k8s.io/client-go/listers/autoscaling/v2beta2: removed
- package k8s.io/client-go/informers/autoscaling/v2beta2: removed
- package k8s.io/client-go/applyconfigurations/autoscaling/v2beta1: removed
- package k8s.io/client-go/applyconfigurations/autoscaling/v2beta2: removed
- ./kubernetes.(*Clientset).AutoscalingV2beta1: removed
- ./kubernetes.(*Clientset).AutoscalingV2beta2: removed
- ./kubernetes.Interface.AutoscalingV2beta1: removed
- ./kubernetes.Interface.AutoscalingV2beta2: removed
- package k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1: removed
- package k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2: removed
- package k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1/fake: removed
- ./kubernetes/fake.(*Clientset).AutoscalingV2beta1: removed
- ./kubernetes/fake.(*Clientset).AutoscalingV2beta2: removed
- ./informers/autoscaling.Interface.V2beta1: removed
- ./informers/autoscaling.Interface.V2beta2: removed
- ./tools/cache/synctrack.AsyncTracker.UpstreamHasSynced: removed
- ./tools/cache/synctrack.SingleFileTracker.UpstreamHasSynced: removed
- package k8s.io/client-go/informers/autoscaling/v2beta1: removed
- package k8s.io/client-go/listers/autoscaling/v2beta1: removed
- ./tools/cache.(*RealFIFO).PopBatch: changed from func(ProcessBatchFunc) error to func(ProcessBatchFunc, PopProcessFunc) error
- ./tools/cache.Controller.HasSyncedChecker: added
- ./tools/cache.Pop: removed
- ./tools/cache.Queue.HasSyncedChecker: added
- ./tools/cache.QueueWithBatch.PopBatch: changed from func(ProcessBatchFunc) error to func(ProcessBatchFunc, PopProcessFunc) error
- ./tools/cache.ResourceEventHandlerRegistration.HasSyncedChecker: added
- ./tools/cache.SharedIndexInformer: no longer implements ./tools/cache.ResourceEventHandlerRegistration
- ./tools/cache.SharedInformer: no longer implements ./tools/cache.ResourceEventHandlerRegistration
- ./tools/cache.Store.Bookmark: added
- ./tools/cache.Store.LastStoreSyncResourceVersion: added
- ./tools/cache.ThreadSafeStore.Bookmark: added
- ./tools/cache.ThreadSafeStore.DeleteWithObject: added
- ./tools/cache.ThreadSafeStore.LastStoreSyncResourceVersion: added
```

I think the following messages about `SharedInformer` can be ignored:
- `no longer implements ./tools/cache.Controller`: cache.Controller is for all practical purposes an internal interface. It should not have been an interface at all ([PR pending](https://github.com/kubernetes/kubernetes/pull/136941)). That it is an interface just adds noise to the apidiff output.
- `no longer implements ./tools/cache.ResourceEventHandlerRegistration`: a `SharedInformer` was never meant to have the same methods as `ResourceEventHandlerRegistration`, that just happened to be the case.

This is a valid API diff caused by https://github.com/kubernetes/kubernetes/pull/135395:
```
- ./tools/cache.ResourceEventHandlerRegistration.HasSyncedChecker: added
```

SharedInformerFactory implementations have to be updated, but that is true in 1.36 also for other reasons.

Comment (pohly) [reply staging/src/k8s.io/client-go/tools/cache/shared_informer.go:207]: /test pull-kubernetes-apidiff

Comment (pohly) [reply staging/src/k8s.io/client-go/tools/cache/shared_informer.go:207]: > This is a valid API diff caused by https://github.com/kubernetes/kubernetes/pull/135395:
>
> - ./tools/cache.ResourceEventHandlerRegistration.HasSyncedChecker: added
>
> SharedInformerFactory implementations have to be updated, but that is true in 1.36 also for other reasons.

... and it is the remaining reason why controller-runtime doesn't build (https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/137056/pull-kubernetes-apidiff/2023458170667536384/build-log.txt):

```
pkg/controller/controllertest/util.go:81:9: cannot use &fakeHandlerRegistration{…} (value of type *fakeHandlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: *fakeHandlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
```

I can keep `cache.ResourceEventHandlerRegistration` unchanged, but that will have a bigger impact on users of client-go than not exposing `SharedInformer.HasSyncedChecker` because they then have to jump through additional hoops when trying to wait for event delivery.

With `SharedInformer.HasSyncedChecker`, the generated `informerFactory.WaitForCacheSync` handles it for them. With event handlers, it's on users.

Having said that, if people care then I can also eliminate that difference.

Comment (alvaroaleman) [reply staging/src/k8s.io/client-go/tools/cache/shared_informer.go:207]: In controller-runtime, we will implement this in the fake regardless of if the existing interface is changed or not

Comment (pohly) [reply staging/src/k8s.io/client-go/tools/cache/shared_informer.go:207]: Here's a cleaner API diff of my original PR + this one here:
```
$ hack/apidiff.sh -r 59cddedb04dcb2c3c5550e9f508b9771ba99f29c -t HEAD ./staging/src/k8s.io/client-go/tools/cache
Checking 3324838231b6237d5883c84820e96c870ecf9509 (= v1.36.0-alpha.1-50-g3324838231b) for API changes since 59cddedb04dcb2c3c5550e9f508b9771ba99f29c (= v1.36.0-alpha.1-46-g59cddedb04d).
Installing apidiff into /tmp/tmp.Bpn5qWX6rX.
Preparing worktree (detached HEAD 3324838231b)
HEAD is now at 3324838231b client-go cache: restore SharedInformerCache interface from <= 1.35
Preparing worktree (detached HEAD 59cddedb04d)
HEAD is now at 59cddedb04d Merge pull request #136901 from Phaow/vac-fix

## ./staging/src/k8s.io/client-go/tools/cache
! second, different message for obj type k8s.io/client-go/tools/cache.SharedIndexInformer interface{AddIndexers(indexers k8s.io/client-go/tools/cache.Indexers) error; GetIndexer() k8s.io/client-go/tools/cache.Indexer; k8s.io/client-go/tools/cache.SharedInformer}, isNew false, part ""
  first:  no longer implements ./tools/cache.ResourceEventHandlerRegistration
  second: no longer implements ./tools/cache.Controller
! second, different message for obj type k8s.io/client-go/tools/cache.SharedInformer interface{AddEventHandler(handler k8s.io/client-go/tools/cache.ResourceEventHandler) (k8s.io/client-go/tools/cache.ResourceEventHandlerRegistration, error); AddEventHandlerWithOptions(handler k8s.io/client-go/tools/cache.ResourceEventHandler, options k8s.io/client-go/tools/cache.HandlerOptions) (k8s.io/client-go/tools/cache.ResourceEventHandlerRegistration, error); AddEventHandlerWithResyncPeriod(handler k8s.io/client-go/tools/cache.ResourceEventHandler, resyncPeriod time.Duration) (k8s.io/client-go/tools/cache.ResourceEventHandlerRegistration, error); GetController() k8s.io/client-go/tools/cache.Controller; GetStore() k8s.io/client-go/tools/cache.Store; HasSynced() bool; IsStopped() bool; LastSyncResourceVersion() string; RemoveEventHandler(handle k8s.io/client-go/tools/cache.ResourceEventHandlerRegistration) error; Run(stopCh <-chan struct{}); RunWithContext(ctx context.Context); SetTransform(handler k8s.io/client-go/tools/cache.TransformFunc) error; SetWatchErrorHandler(handler k8s.io/client-go/tools/cache.WatchErrorHandler) error; SetWatchErrorHandlerWithContext(handler k8s.io/client-go/tools/cache.WatchErrorHandlerWithContext) error}, isNew false, part ""
  first:  no longer implements ./tools/cache.ResourceEventHandlerRegistration
  second: no longer implements ./tools/cache.Controller
Incompatible changes:
- ./tools/cache/synctrack.AsyncTracker.UpstreamHasSynced: removed
- ./tools/cache/synctrack.SingleFileTracker.UpstreamHasSynced: removed
- ./tools/cache.Controller.HasSyncedChecker: added
- ./tools/cache.Queue.HasSyncedChecker: added
- ./tools/cache.ResourceEventHandlerRegistration.HasSyncedChecker: added
- ./tools/cache.SharedIndexInformer: no longer implements ./tools/cache.Controller
- ./tools/cache.SharedInformer: no longer implements ./tools/cache.Controller
```

File: staging/src/k8s.io/dynamic-resource-allocation/resourceslice/tracker/tracker.go [hunk 3]
```diff
@@ -256,7 +256,9 @@ func (t *Tracker) HasSynced() bool {
 
 func (t *Tracker) HasSyncedChecker() cache.DoneChecker {
 	if !t.enableDeviceTaintRules {
-		return t.resourceSlices.HasSyncedChecker()
+		// t.resourceSlices is a SharedInformer created by client-go,
+		// so we can do an unchecked type cast.
+		return t.resourceSlices.(cache.HasSyncedChecker).HasSyncedChecker()
```
Comment (pohly) [inline staging/src/k8s.io/dynamic-resource-allocation/resourceslice/tracker/tracker.go:261]: This is one of those places that get more ugly when `HasSyncedChecker` is not provided directly by `SharedInformer`: the code here cannot use `DoneCheckerForInformer` because it has no context that could be used to control the goroutine that potentially might get created by that helper.

An unchecked type assertion is the lesser evil and okay because we know where the SharedInformer comes from.
