### ISSUE TITLE
golang tip br0ken! ci-kubernetes-e2e-kind-golang-tip and ci-kubernetes-unit-golang-tip are failing

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#139159]
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-golang-tip
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-golang-tip
Above jobs have been failing since the merge of https://github.com/golang/go/commit/e62d3e6e897175a07aa44a7b2c7f99700072f22f

**Comment by liggitt** [comment]
@Jefftree @jpbetz looks like the kube-openapi update in https://github.com/kubernetes/kube-openapi/pull/604 to be closer to json-experiment HEAD started relying on particular json/v2 aspects which have evolved since then

```
vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/alias.go:618:21: undefined: json.SkipFunc
vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/alias.go:957:14: undefined: json.DiscardUnknownMembers
```

I think we need to bump kube-openapi to json-experiment HEAD in order to be compatible with stdlib json/v2 as it will ship in Go 1.27

/assign @Jefftree

**Comment by liggitt** [comment]
@jpbetz we also will need to adjust unit tests that exercise behavior of invalid UTF-8 to tolerate munged output:

```
{Failed  === RUN   TestCollectionsEncoding/Normal/UnstructuredList_object_invalid_UTF-8_
    collections_test.go:579: encoded: {"items":[],"key":"�"}
    collections_test.go:581: not matching:
          string(
        - 	"{\"items\":[],\"key\":\"�\"}\n",
        + 	"{\"items\":[],\"key\":\"\\ufffd\"}\n",
          )
```

**Comment by jpbetz** [comment]
> [@jpbetz](https://github.com/jpbetz) we also will need to adjust unit tests that exercise behavior of invalid UTF-8 to tolerate munged output:
> 
> ```
> {Failed  === RUN   TestCollectionsEncoding/Normal/UnstructuredList_object_invalid_UTF-8_
>     collections_test.go:579: encoded: {"items":[],"key":"�"}
>     collections_test.go:581: not matching:
>           string(
>         - 	"{\"items\":[],\"key\":\"�\"}\n",
>         + 	"{\"items\":[],\"key\":\"\\ufffd\"}\n",
>           )
> ```

I've opened https://github.com/kubernetes/kubernetes/pull/139163 to tolerate this

**Comment by liggitt** [comment]
once https://github.com/kubernetes/kubernetes/pull/139173 merges this should be green again

**Comment by liggitt** [comment]
green e2e run

Latest unit test run passed all packages except a known DRA flake also failing on regular unit runs

**Comment by dims** [comment]
<img width="3442" height="998" alt="Image" src="https://github.com/user-attachments/assets/17089e0c-f6d5-45ed-8cea-ee3cbb361db5" />
