### ISSUE TITLE
[1.28.2] Keeps zfs pool busy on UnmountVolume via csi-provider

### ISSUE THREAD

**Issue by thoro** [kubernetes/kubernetes#120919]
### What happened?

We are running our custom csi provider to mount zfs via iscsi, this is operating since at least 1.20 and never showed any issues.

It does not implement the NodeStage / NodeUnstage apis, and only uses the NodePublishVolume / NodeUnpublishVolume.

Since upgrading to 1.28.2 the Unmount progress gets stuck and the zfs pool keeps busy indefinitely.

A solution to fix the stuck pool is to delete the folder of the pv inside of the pod, this leads to log spam by kubelet it can't find the corresponding .json file for the csi provider, and a restart of kubelet afterwards allows the pool to be actually exported.

### What did you expect to happen?

Do not keep the mounted volume busy when Unmounting via CSI providers.

### How can we reproduce it (as minimally and precisely as possible)?

Possibly other providers also see those issues?

### Anything else we need to know?

Kubelet logs the following, whereas the message is passed from the csi plugin:

```
Sep 28 08:18:26 at-host-41 kubelet[3179792]: E0928 08:18:26.861506 3179792 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/anchor.storage.creamfinance.com^v-758fa692-ad4d-4cc5-8f20-18b8770bcbd5 podName:3741aca2-e297-4d4c-a2ff-3978a62f043e nodeName:}" failed. No retries permitted until 2023-09-28 08:20:28.861466917 +0000 UTC m=+1190473.720166002 (durationBeforeRetry 2m2s). Error: UnmountVolume.TearDown failed for volume "pgdata" (UniqueName: "kubernetes.io/csi/anchor.storage.creamfinance.com^v-758fa692-ad4d-4cc5-8f20-18b8770bcbd5") pod "3741aca2-e297-4d4c-a2ff-3978a62f043e" (UID: "3741aca2-e297-4d4c-a2ff-3978a62f043e") : kubernetes.io/csi: Unmounter.TearDownAt failed: rpc error: code = Internal desc = cannot export 'v-758fa692-ad4d-4cc5-8f20-18b8770bcbd5': pool is busy (exit status 1)
```

When deleting the corresponding directory (/var/lib/kubelet/pods/3741aca2-e297-4d4c-a2ff-3978a62f043e/volumes/kubernetes.io~csi/pv-758fa692-ad4d-4cc5-8f20-18b8770bcbd5) as described, it spams the log with following message:

```
Sep 28 08:19:54 at-host-41 kubelet[3179792]: E0928 08:19:54.761566 3179792 reconciler_common.go:169] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"pgdata\" (UniqueName: \"kubernetes.io/csi/anchor.storage.creamfinance.com^v-758fa692-ad4d-4cc5-8f20-18b8770bcbd5\") pod \"3741aca2-e297-4d4c-a2ff-3978a62f043e\" (UID: \"3741aca2-e297-4d4c-a2ff-3978a62f043e\") : UnmountVolume.NewUnmounter failed for volume \"pgdata\" (UniqueName: \"kubernetes.io/csi/anchor.storage.creamfinance.com^v-758fa692-ad4d-4cc5-8f20-18b8770bcbd5\") pod \"3741aca2-e297-4d4c-a2ff-3978a62f043e\" (UID: \"3741aca2-e297-4d4c-a2ff-3978a62f043e\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/3741aca2-e297-4d4c-a2ff-3978a62f043e/volumes/kubernetes.io~csi/pv-758fa692-ad4d-4cc5-8f20-18b8770bcbd5/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/3741aca2-e297-4d4c-a2ff-3978a62f043e/volumes/kubernetes.io~csi/pv-758fa692-ad4d-4cc5-8f20-18b8770bcbd5/vol_data.json]: open /var/lib/kubelet/pods/3741aca2-e297-4d4c-a2ff-3978a62f043e/volumes/kubernetes.io~csi/pv-758fa692-ad4d-4cc5-8f20-18b8770bcbd5/vol_data.json: no such file or directory" err="UnmountVolume.NewUnmounter failed for volume \"pgdata\" (UniqueName: \"kubernetes.io/csi/anchor.storage.creamfinance.com^v-758fa692-ad4d-4cc5-8f20-18b8770bcbd5\") pod \"3741aca2-e297-4d4c-a2ff-3978a62f043e\" (UID: \"3741aca2-e297-4d4c-a2ff-3978a62f043e\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/3741aca2-e297-4d4c-a2ff-3978a62f043e/volumes/kubernetes.io~csi/pv-758fa692-ad4d-4cc5-8f20-18b8770bcbd5/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/3741aca2-e297-4d4c-a2ff-3978a62f043e/volumes/kubernetes.io~csi/pv-758fa692-ad4d-4cc5-8f20-18b8770bcbd5/vol_data.json]: open /var/lib/kubelet/pods/3741aca2-e297-4d4c-a2ff-3978a62f043e/volumes/kubernetes.io~csi/pv-758fa692-ad4d-4cc5-8f20-18b8770bcbd5/vol_data.json: no such file or directory"
```

### Kubernetes version

<details>

```console
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

</details>

### Cloud provider

<details>
on-premise
</details>

### OS version

<details>

```console
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1
# paste output here
Linux at-host-41 5.14.0-162.23.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Apr 11 19:09:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

```console
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
# paste output here
Linux at-host-46 5.10.37 #1 SMP Mon May 17 13:15:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

Custom CSI provider with quay.io/k8scsi/csi-node-driver-registrar:v1.3.0

</details>

**Comment by thoro** [comment]
Great, writing this out solved it for me, but I'm not fully clear why.

Deleting the mount directory inside of /var/lib/kubelet/pods/3741aca2-e297-4d4c-a2ff-3978a62f043e/volumes/kubernetes.io~csi/pv-758fa692-ad4d-4cc5-8f20-18b8770bcbd5 releases the "busy" pool and allows to proceed with the unmount.

In the operator I was first exporting the zfs pool and then deleting the mount folder, I have switched those two steps and now it seems to work correctly again.
