### ISSUE TITLE
missing method getAvailableDriveLetter when testing on windows

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#52605]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig windows

**What happened**:

```
$ GOOS=windows go test -v k8s.io/kubernetes/pkg/util/mount
# k8s.io/kubernetes/pkg/util/mount
pkg/util/mount/mount_windows_test.go:26: undefined: getAvailableDriveLetter
FAIL	k8s.io/kubernetes/pkg/util/mount [build failed]
```

This bug was introduced in #51252. @andyzhangx Please fix it.

/cc @brendandburns

**What you expected to happen**:
Should include the definition of `getAvailableDriveLetter()`

**How to reproduce it (as minimally and precisely as possible)**:
As above

**Anything else we need to know?**:

**Environment**:
Kubernetes master branch

**Comment by andyzhangx** [comment]
https://github.com/kubernetes/kubernetes/pull/52469 will fix this issue, just comment TestGetAvailableDriveLetter test case if it's blocking you, thankx.

**Comment by andyzhangx** [comment]
#52469 is merged

**Comment by andyzhangx** [comment]
@dixudx could you close this issue? Thanks.
