### ISSUE TITLE
Unable to compile on Mac

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#37400]
```
# k8s.io/kubernetes/pkg/kubelet/eviction
pkg/kubelet/eviction/threshold_notifier.go:20:10: fatal error: 'sys/eventfd.h' file not found
#include <sys/eventfd.h>
         ^
1 error generated.
```

Caused by #32577 - needs to be gated by a build guard.

**Comment by smarterclayton** [comment]
Dupe of #37384
