### PR TITLE
Automated cherry pick of #29119

### PR DESCRIPTION
**Pull request by pmorie**
Cherry pick of #29119 on release-1.3.

### CODE REVIEW

**Comment by fejta** [comment]
@k8s-bot test this issue #29966

**Comment by saad-ali** [comment]
```
Verifying ./hack/../hack/verify-boilerplate.sh
Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager_test.go
FAILED   ./hack/../hack/verify-boilerplate.sh	1s
```

Because https://github.com/kubernetes/kubernetes/pull/26755 hasn't been cherry-picked you'll need to fix this manually for this cherry pick.

```
pkg/kubelet/volumemanager/volume_manager_test.go:193: too many arguments in call to NewVolumeManager
kg/conversion	2.836s
...
FAIL	k8s.io/kubernetes/pkg/kubelet/volumemanager [build failed]
```

Bad merge?

**Comment by pmorie** [comment]
I'll take a look, was wondering about that.

**Comment by fabioy** [comment]
Argh, bad click habits. Please resolve the build/verification issues. I'll LGTM it then. Thanks.

**Comment by pmorie** [comment]
@fabioy okay, it's on my list for tonight
