### ISSUE TITLE
CalculateExpectedPodCountFailed events occur intermittently on supported resources.

### ISSUE THREAD

**Issue by adammw** [kubernetes/kubernetes#109954]
### What happened?

We frequently see events on PodDisruptionBudgets consisting of: 
```
reason=CalculateExpectedPodCountFailed message=Failed to calculate the number of expected pods: replicasets.apps does not implement the scale subresource
```

As stated in the [API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#read-scale-replicaset-v1-apps), replicasets.apps clearly does implement the scale subresource.

### What did you expect to happen?

CalculateExpectedPodCountFailed events not to occur.

### How can we reproduce it (as minimally and precisely as possible)?

It seems to be an intermittent error, I believe it is a race condition that occurs when a Deployment is progressing and a replicaset and its pods are being deleted.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EC2
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux ip-172-16-114-137.us-west-2.compute.internal 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:10:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by adammw** [comment]
Attaching a debugger and I managed to catch it happening, looks like the issue is implementsScale() as introduced in #98346 incorrectly checks the Kind matches when the scale subresource always has a Kind of `Scale`.
cc @mortent 

![Screen Shot 2022-05-11 at 4 00 03 pm](https://user-images.githubusercontent.com/153219/167779382-2c7778eb-601c-4a74-8601-46dd82d5132b.png)

**Comment by adammw** [comment]
/reopen

This race condition should be resolved to avoid noisy events.

**Comment by adammw** [comment]
/reopen

This is still occurring on our v1.29 clusters.

**Comment by adammw** [comment]
Specifically, we are getting
`Failed to calculate the number of expected pods: daemonsets.apps does not implement the scale subresource`
and `Failed to calculate the number of expected pods: jobs.batch does not implement the scale subresource`. Which might be true that they don't implement scale?

**Comment by adammw** [comment]
Which sounds more like #108124 ...
