### ISSUE TITLE
Compilation error on OSX: undefined: procfs.PKill

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#30886]
Compiling fails on OSX/MacOS:

````
make WHAT=pkg/kubelet GOFLAGS=-v
# k8s.io/kubernetes/pkg/kubelet
pkg/kubelet/container_bridge.go:59: undefined: procfs.PKill
pkg/kubelet/kubelet.go:404: undefined: procfs.NewProcFS
make: *** [all] Error 1
```

**Comment by dchen1107** [comment]
Caused by https://github.com/kubernetes/kubernetes/pull/30087? 

cc/ @dims

**Comment by johscheuer** [comment]
Yes this is caused by https://github.com/kubernetes/kubernetes/pull/30087 and https://github.com/kubernetes/kubernetes/pull/30723 didn't fixed it for OSX/unsupported OS. I fixed the unsupported file https://github.com/kubernetes/kubernetes/pull/30887

**Comment by dims** [comment]
@johscheuer thanks!

**Comment by dchen1107** [comment]
@johscheuer Thanks for fixing.
