### PR TITLE
Remove kubelet pkill dependency

### PR DESCRIPTION
**Pull request by dims**
Issue #26093 identified pkill as one of the dependencies of kublet
which could be worked around.  Build on the code introduced for pidof
and regexp for the process(es) we need to send a signal to.

Related to #26093

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30087)

### CODE REVIEW

**Comment by yujuhong** [comment]
Is this ready for review or WIP as the commit suggests?

**Comment by dims** [comment]
@yujuhong it's WIP as i am trying to write tests for it. Also needs the other PR to merge. Thanks!

File: pkg/util/procfs/procfs_test.go [hunk 1]
```diff
@@ -56,3 +59,17 @@ func TestContainerNameFromProcCgroup(t *testing.T) {
...
 }
+
+func TestPidOf(t *testing.T) {
+	if runtime.GOOS == "darwin" || runtime.GOOS == "windows" {
+		t.Skipf("not supported on GOOS=%s", runtime.GOOS)
+	}
+	// Let's look for the init process
+	pids, _ := PidOf("init")
+	// test-unit-integration environment is slightly different
+	if len(pids) == 0 {
```
Comment (philips) [inline pkg/util/procfs/procfs_test.go]: is there a better way to detect this environment? I don't like this heuristic based guess.

Comment (dims) [inline pkg/util/procfs/procfs_test.go]: Ack. I'll figure out a better way in the other PR 

https://github.com/kubernetes/kubernetes/pull/30002/

**Comment by dims** [comment]
@yujuhong This PR is ready now. The other PR that this depended on was merged last night

File: pkg/util/procfs/procfs.go [hunk 2]
```diff
@@ -62,7 +64,38 @@ func (pfs *ProcFS) GetFullContainerName(pid int) (string, error) {
...
+	if len(name) == 0 {
+		return fmt.Errorf("Name should not be empty")
+	}
+	re, err := regexp.Compile(name)
+	if err != nil {
+		return err
+	}
+	pids := getPids(re)
+	if len(pids) == 0 {
+		return fmt.Errorf("Unable to fetch pids for process name : %s", name)
```
Comment (yujuhong) [inline pkg/util/procfs/procfs.go]: nit: s/Unable/unable
nit: s/%s/%q

File: pkg/util/procfs/procfs.go [hunk 3]
```diff
@@ -62,7 +64,38 @@ func (pfs *ProcFS) GetFullContainerName(pid int) (string, error) {
...
+	}
+	for _, pid := range pids {
+		if err = syscall.Kill(pid, sig); err != nil {
```
Comment (yujuhong) [inline pkg/util/procfs/procfs.go]: This is slightly different from `pkill`'s behavior. `pkill` would continue killing all matching processes.

File: pkg/util/procfs/procfs.go [hunk 4]
```diff
@@ -62,7 +64,38 @@ func (pfs *ProcFS) GetFullContainerName(pid int) (string, error) {
...
+			return err
+		}
+	}
+	return nil
+}
+
+func PidOf(name string) ([]int, error) {
+	if len(name) == 0 {
+		return []int{}, fmt.Errorf("Name should not be empty")
```
Comment (yujuhong) [inline pkg/util/procfs/procfs.go]: s/Name/name

File: pkg/util/procfs/procfs.go [hunk 5]
```diff
@@ -62,7 +64,38 @@ func (pfs *ProcFS) GetFullContainerName(pid int) (string, error) {
 	return containerNameFromProcCgroup(string(content))
 }
 
-func PidOf(name string) []int {
+func PKill(name string, sig syscall.Signal) error {
+	if len(name) == 0 {
+		return fmt.Errorf("Name should not be empty")
```
Comment (yujuhong) [inline pkg/util/procfs/procfs.go]: s/Name/name

error messages should not be capitalized.

File: pkg/util/procfs/procfs.go (hunk 2 above)
Comment (dims) [inline pkg/util/procfs/procfs.go]: ack fixing

File: pkg/util/procfs/procfs.go (hunk 4 above)
Comment (dims) [inline pkg/util/procfs/procfs.go]: ack fixing

File: pkg/util/procfs/procfs.go (hunk 5 above)
Comment (dims) [inline pkg/util/procfs/procfs.go]: ack fixing

File: pkg/util/procfs/procfs.go [hunk 6]
```diff
@@ -62,7 +65,42 @@ func (pfs *ProcFS) GetFullContainerName(pid int) (string, error) {
...
+		return fmt.Errorf("unable to fetch pids for process name : %q", name)
+	}
+	errList := []error{}
+	for _, pid := range pids {
+		if err = syscall.Kill(pid, sig); err != nil {
+			errList = append(errList, err)
+		}
+	}
+	if len(errList) > 0 {
+		return utilerrors.NewAggregate(errList)
```
Comment (yujuhong) [inline pkg/util/procfs/procfs.go]: nit: just return `utilerrors.NewAggregate(errList)`. `NewAggregate` returns `nil` if `errList` is empty.

File: pkg/util/procfs/procfs.go [hunk 7]
```diff
@@ -62,7 +65,42 @@ func (pfs *ProcFS) GetFullContainerName(pid int) (string, error) {
 	return containerNameFromProcCgroup(string(content))
 }
 
-func PidOf(name string) []int {
+func PKill(name string, sig syscall.Signal) error {
```
Comment (yujuhong) [inline pkg/util/procfs/procfs.go]: Add godoc style comment for the function.

File: pkg/util/procfs/procfs.go [hunk 8]
```diff
@@ -62,7 +65,42 @@ func (pfs *ProcFS) GetFullContainerName(pid int) (string, error) {
...
+		return []int{}, fmt.Errorf("name should not be empty")
+	}
+	re, err := regexp.Compile("(^|/)" + name + "$")
+	if err != nil {
+		return []int{}, err
+	}
+	return getPids(re), nil
+}
+
+func getPids(re *regexp.Regexp) []int {
```
Comment (yujuhong) [inline pkg/util/procfs/procfs.go]: Add godoc style comment for the function.

File: pkg/util/procfs/procfs_test.go [hunk 9]
```diff
@@ -66,7 +69,27 @@ func TestPidOf(t *testing.T) {
...
+	c := make(chan os.Signal, 1)
+	signal.Notify(c, sig)
+	defer signal.Stop(c)
+	PKill(os.Args[0], sig)
+	select {
+	case s := <-c:
+		if s != sig {
+			t.Fatalf("signal was %v, want %v", s, sig)
+		}
+	case <-time.After(1 * time.Second):
```
Comment (yujuhong) [inline pkg/util/procfs/procfs_test.go]: Would this test flake under load -- is 1 second enough?

File: pkg/util/procfs/procfs.go (hunk 6 above)
Comment (dims) [inline pkg/util/procfs/procfs.go]: Aha. Right. fixing

File: pkg/util/procfs/procfs_test.go (hunk 9 above)
Comment (dims) [inline pkg/util/procfs/procfs_test.go]: I think so, in all the runs so far, it has not failed yet

Comment (yujuhong) [inline pkg/util/procfs/procfs_test.go]: Suggest change this to wait.ForeverTestTimeout just to be safe.

File: pkg/util/procfs/procfs.go (hunk 8 above)
Comment (dims) [inline pkg/util/procfs/procfs.go]: Ack

File: pkg/util/procfs/procfs.go (hunk 7 above)
Comment (dims) [inline pkg/util/procfs/procfs.go]: Ack

File: pkg/util/procfs/procfs_test.go (hunk 9 above)
Comment (dims) [inline pkg/util/procfs/procfs_test.go]: @yujuhong : please see https://github.com/golang/go/blob/master/src/os/signal/signal_test.go#L27 and the TestSIGCONT from where waitSig is called. If you still want me to change it, please let me know.

**Comment by dims** [comment]
k8s-bot test this issue: #IGNORE

**Comment by dims** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by ixdy** [comment]
This broke the Windows build (along with #27970).
```
+++ [0816 15:23:49] windows/amd64: go build started
# k8s.io/kubernetes/pkg/util/mount
pkg/util/mount/mount.go:89: cannot use Mounter literal (type *Mounter) as type Interface in return argument:
        *Mounter does not implement Interface (missing GetDeviceNameFromMount method)
# k8s.io/kubernetes/pkg/util/procfs
pkg/util/procfs/procfs.go:84: undefined: syscall.Kill
```
cc @k8s-oncall

**Comment by krousey** [comment]
@ixdy Are we trying to build every package on Windows? Or just the binaries we care about?

**Comment by krousey** [comment]
@ixdy Another question, is the appropriate action here reverting? Or forward fix?

**Comment by ixdy** [comment]
We build client and test targets for Windows. It looks like one of the test targets (not sure which one) is what depends on this package.

A forward fix is fine if we can get one soon. We're trying to re-enable a full `make release` on Jenkins (https://github.com/kubernetes/test-infra/issues/393) and this breakage is one thing blocking that.

**Comment by yujuhong** [comment]
FYI, I posted a fix #30723, but haven't verified it yet.
