### PR TITLE
fix cross build failure

### LINKED ISSUE #48234: Cross build failed in unsupportedContainerManager
```
I0628 18:33:54.041] # k8s.io/kubernetes/pkg/kubelet/cm
I0628 18:33:54.041] pkg/kubelet/cm/container_manager_unsupported.go:33: cannot use unsupportedContainerManager literal (type *unsupportedContainerManager) as type ContainerManager in assignment:
I0628 18:33:54.042] 	*unsupportedContainerManager does not implement ContainerManager (missing GetCapacity method)
I0628 18:33:54.042] pkg/kubelet/cm/container_manager_unsupported.go:72: cannot use unsupportedContainerManager literal (type *unsupportedContainerManager) as type ContainerManager in return argument:
I0628 18:33:54.042] 	*unsupportedContainerManager does not implement ContainerManager (missing GetCapacity method)
```
It was introduced by https://github.com/kubernetes/kubernetes/pull/48123/files

cc/ @msau42

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #48234

### CODE REVIEW

**Comment by caesarxuchao** [comment]
cc @msau42

**Comment by caesarxuchao** [comment]
Close in favor to #48235.

**Comment by xiangpengzhao** [comment]
@caesarxuchao Didn't know you were online or not, so I sent that PR in order to fix it ASAP:)

**Comment by caesarxuchao** [comment]
Thanks a lot @xiangpengzhao
