### ISSUE TITLE
failed readiness probes not reporting events

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#46241]
**Is this a BUG REPORT or FEATURE REQUEST?**
BUG REPORT

**Kubernetes version** (use `kubectl version`):
kubernetes/master using CRI with docker

**What happened**:

Create a pod that uses a readiness probe that does an exec to command that doesnt exist

```
$ kubectl create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/tc533910/readiness-probe-exec.yaml
```

See the following in logs:

```
cat /tmp/kubelet.log
I0522 16:21:05.941271   12546 prober.go:106] Readiness probe for "hello-pod_default(231fd935-3f2c-11e7-bc2e-c85b76cda386):hello-pod" failed (failure): rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"/bin/hello\\\": stat /bin/hello: no such file or directory\"\n"
E0522 16:21:05.941351   12546 event.go:260] Could not construct reference to: '&v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"hello-pod", UID:"231fd935-3f2c-11e7-bc2e-c85b76cda386", APIVersion:"v1", ResourceVersion:"234", FieldPath:"spec.containers{hello-pod}"}' due to: 'object does not implement the List interfaces'. Will not report event: 'Warning' 'Unhealthy' 'Readiness probe failed: rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"/bin/hello\\\": stat /bin/hello: no such file or directory\"\n"
```

**What you expected to happen**:
No error in log, expected the event to properly be thrown.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else we need to know**:
Nope.

**Comment by derekwaynecarr** [comment]
this is a regression.

@kubernetes/sig-node-bugs

**Comment by derekwaynecarr** [comment]
debugging, will post a fix once found.

**Comment by ncdc** [comment]
Other reports: #44348, #44652

**Comment by derekwaynecarr** [comment]
@ncdc -- thanks for the other reports.  at least now we have a reliable reproduction.

**Comment by derekwaynecarr** [comment]
The problem appears to be the following:

1. the `kubelet` has a `ReffManager` that  correlates containers to a `v1.ObjectReference`.  It uses the type `k8s.io/kubernetes/pkg/api/v1` `ObjectReference`.
1. the event recorder library we use in the prober works with `k8s.io/client-go/pkg/api/v1` `ObjectReference`.  If it doesn't get one of those, it expects the passed in object to implement List.

As a result, we are passing a v1.ObjectReference the recorder was not expecting.

**Comment by yujuhong** [comment]
The bug may have been introduced in #40710, which was there since v1.6.0.

**Comment by derekwaynecarr** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/46246 for a fix.

**Comment by yujuhong** [comment]
Keep this open until 1.6 is patched.

**Comment by spiffxp** [comment]
/remove-priority P0
/priority critical-urgent
(I'm not actually sure this is the right priority, just trying to remove the old priority/PN labels)

**Comment by yujuhong** [comment]
Closing since #48099 has been merged.
