### PR TITLE
Use log functions of core framework on test/e2e/scheduling

### PR DESCRIPTION
**Pull request by s-ito-ts**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
This makes test/e2e/scheduling/* to use log functions of core framework.

**Which issue(s) this PR fixes**:
Ref: #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by hex108 — APPROVED** [review]
Thanks @s-ito-ts 

/lgtm
/assign @Huang-Wei

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve
/retest

**Comment by pohly** [comment]
This change works on its own, but not in combination with some other PRs:
https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=batch&pull=master%2C81947%2C81973%2C81982%2C81990%2C81993

I propose we hold this less important PR ("cleanup", no priority set) until the merge pool is smaller.

/hold

**Comment by Huang-Wei** [comment]
@s-ito-ts you may need to take a look at the CI failure.

**Comment by oomichi** [comment]
> @s-ito-ts you may need to take a look at the CI failure.

As @Huang-Wei said, this test failure is due to this change itself.
According to https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/81982/pull-kubernetes-bazel-build/1167193535053565953/build-log.txt
the error message is 
```
/b/f/w/test/e2e/scheduling/predicates.go:101:4: undefined: e2elog
```
So e2elog has been added at predicates.go:101 after proposing this PR and the CI job is failed now.
We need to update this PR.
(pull-kubernetes-bazel-build tends to be stable, not flake. If that is failed continuously, it is better to check the log from the above `Details`)

/hold
