### PR TITLE
Fix cross build introduced in d494ef66f0c167d1ba8a91cb29279bb7293588d3

### PR DESCRIPTION
**Pull request by kad**
**What this PR does / why we need it**: fix cross build on non-Linux OS introduced in d494ef66f0

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
```console
+++ [1106 11:07:34] linux/amd64: go build started
+++ [1106 11:10:33] linux/amd64: go build finished
+++ [1106 11:07:34] darwin/amd64: go build started
+++ [1106 11:11:04] darwin/amd64: go build finished
+++ [1106 11:07:34] windows/amd64: go build started
# k8s.io/kubernetes/pkg/volume
pkg/volume/metrics_du.go:78: undefined: util.Find
pkg/volume/metrics_du.go:89: assignment count mismatch: 7 = 4
pkg/volume/metrics_statfs.go:57: assignment count mismatch: 7 = 4
Makefile:79: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:264: recipe for target 'cross' failed
make: *** [cross] Error 1
Makefile:248: recipe for target 'release' failed
make: *** [release] Error 1
```

**Release note**:
```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36307)

### CODE REVIEW

**Comment by kad** [comment]
#36313 has better fix.
