### ISSUE TITLE
Build not working properly

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#34448]
If I'm not missing something our incremental-ish build works very very badly. It failed to noticed that the file something depends on got recompiled, and thus failed to fail the build.

I observe the following:

```
gmarek@breakwater:~/go/src/k8s.io/kubernetes$ grep -Rn "RCConfig" test
test/utils/runners.go:43:type RCConfig struct {
test/utils/runners.go:95:func (rc *RCConfig) Log(fmt string, args ...interface{}) {
test/utils/runners.go:103:  RCConfig
test/utils/runners.go:107:  RCConfig
test/utils/runners.go:218:func RunRC(config RCConfig) error {
test/utils/runners.go:226:func (config *RCConfig) create() error {
test/utils/runners.go:271:func (config *RCConfig) applyTo(template *api.PodTemplateSpec) {
test/utils/runners.go:493:func (config *RCConfig) start() error {
test/e2e/cluster_size_autoscaling.go:459:   config := &framework.RCConfig{
test/e2e/cluster_size_autoscaling.go:478:   config := &framework.RCConfig{
test/e2e/cluster_size_autoscaling.go:497:   config := &framework.RCConfig{
test/e2e/cluster_size_autoscaling.go:513:   config := &framework.RCConfig{
test/e2e/proxy.go:119:      cfg := framework.RCConfig{
test/e2e/daemon_restart.go:193: var config framework.RCConfig
test/e2e/daemon_restart.go:206:     config = framework.RCConfig{
test/e2e/kubelet_perf.go:71:    Expect(framework.RunRC(framework.RCConfig{
test/e2e/kubelet.go:189:                Expect(framework.RunRC(framework.RCConfig{
test/e2e/service_latency.go:118:    cfg := framework.RCConfig{
test/e2e/etcd_failure.go:43:        Expect(framework.RunRC(framework.RCConfig{
test/e2e/autoscaling_utils.go:330:  rcConfig := framework.RCConfig{
test/e2e/autoscaling_utils.go:349:          RCConfig: rcConfig,
test/e2e/autoscaling_utils.go:355:          RCConfig: rcConfig,
test/e2e/autoscaling_utils.go:383:  controllerRcConfig := framework.RCConfig{
test/e2e/service.go:1615:   config := framework.RCConfig{
test/e2e/load.go:70:    var configs []*testutils.RCConfig
test/e2e/load.go:149:           configs = generateRCConfigs(totalPods, itArg.image, itArg.command, namespaces)
test/e2e/load.go:287:func generateRCConfigs(totalPods int, image string, command []string, nss []*api.Namespace) []*testutils.RCConfig {
test/e2e/load.go:288:   configs := make([]*testutils.RCConfig, 0)
test/e2e/load.go:291:   configs = append(configs, generateRCConfigsForGroup(nss, smallRCGroupName, smallRCSize, smallRCCount, image, command)...)
test/e2e/load.go:292:   configs = append(configs, generateRCConfigsForGroup(nss, mediumRCGroupName, mediumRCSize, mediumRCCount, image, command)...)
test/e2e/load.go:293:   configs = append(configs, generateRCConfigsForGroup(nss, bigRCGroupName, bigRCSize, bigRCCount, image, command)...)
test/e2e/load.go:308:func generateRCConfigsForGroup(
test/e2e/load.go:309:   nss []*api.Namespace, groupName string, size, count int, image string, command []string) []*testutils.RCConfig {
test/e2e/load.go:310:   configs := make([]*testutils.RCConfig, 0, count)
test/e2e/load.go:312:       config := &testutils.RCConfig{
test/e2e/load.go:330:func generateServicesForConfigs(configs []*testutils.RCConfig) []*api.Service {
test/e2e/load.go:357:func createAllRC(configs []*testutils.RCConfig, creatingTime time.Duration) {
test/e2e/load.go:366:func createRC(wg *sync.WaitGroup, config *testutils.RCConfig, creatingTime time.Duration) {
test/e2e/load.go:374:func scaleAllRC(configs []*testutils.RCConfig, scalingTime time.Duration) {
test/e2e/load.go:385:func scaleRC(wg *sync.WaitGroup, config *testutils.RCConfig, scalingTime time.Duration) {
test/e2e/load.go:402:func deleteAllRC(configs []*testutils.RCConfig, deletingTime time.Duration) {
test/e2e/load.go:411:func deleteRC(wg *sync.WaitGroup, config *testutils.RCConfig, deletingTime time.Duration) {
test/e2e/density.go:57: Configs      []testutils.RCConfig
test/e2e/density.go:475:            RCConfigs := make([]framework.RCConfig, numberOrRCs)
test/e2e/density.go:478:                RCConfigs[i] = framework.RCConfig{Client: c,
test/e2e/density.go:498:                Configs:      RCConfigs,
test/e2e/density.go:696:        RCConfigs := make([]framework.RCConfig, rcCnt)
test/e2e/density.go:703:            RCConfigs[i] = framework.RCConfig{Client: c,
test/e2e/density.go:718:            Configs:      RCConfigs,
gmarek@breakwater:~/go/src/k8s.io/kubernetes$ make
+++ [1010 15:28:46] Generating bindata:
    /usr/local/google/home/gmarek/go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1010 15:28:47] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1010 15:28:47] Building go targets for linux/amd64:
    cmd/kube-dns
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-discovery
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/mungedocs
    cmd/genswaggertypedocs
    cmd/linkcheck
    examples/k8petstore/web-server/src
    federation/cmd/genfeddocs
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
```

Things to look at:
- I moved RCConfig from `test/e2e/framework/util.go` to `test/utils/runners.go` (I want to reuse this code in integration tests, but that doesn't matter)
- even though there's no `framework.RCConfig` anymore everything keeps compiling.

Of course after clean it correctly fails:

```
gmarek@breakwater:~/go/src/k8s.io/kubernetes$ make
+++ [1010 15:46:40] Generating bindata:
    /usr/local/google/home/gmarek/go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
+++ [1010 15:46:40] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [1010 15:46:41] Building go targets for linux/amd64:
    cmd/kube-dns
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-discovery
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/mungedocs
    cmd/genswaggertypedocs
    cmd/linkcheck
    examples/k8petstore/web-server/src
    federation/cmd/genfeddocs
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
# k8s.io/kubernetes/test/e2e
test/e2e/autoscaling_utils.go:305: too many arguments in call to framework.DeleteRCAndPods
test/e2e/autoscaling_utils.go:307: too many arguments in call to framework.DeleteRCAndPods
test/e2e/autoscaling_utils.go:330: undefined: framework.RCConfig
test/e2e/autoscaling_utils.go:345: undefined: framework.RunRC
test/e2e/autoscaling_utils.go:348: undefined: framework.DeploymentConfig
test/e2e/autoscaling_utils.go:351: undefined: framework.RunDeployment
test/e2e/autoscaling_utils.go:354: undefined: framework.ReplicaSetConfig
test/e2e/autoscaling_utils.go:357: undefined: framework.RunReplicaSet
test/e2e/autoscaling_utils.go:383: undefined: framework.RCConfig
test/e2e/restart.go:104: undefined: framework.PodStore
test/e2e/autoscaling_utils.go:383: too many errors
make: *** [all] Error 1
```

cc @thockin @smarterclayton @lavalamp @fejta @timothysc @davidopp @wojtek-t @fgrzadkowski

**Comment by jbeda** [comment]
Hmmm -- this looks like https://github.com/golang/go/issues/3895 but that issue should have been fixed in the version of Go that we are using here.

**Comment by jbeda** [comment]
@gmarek -- are you using the dockerized build?  If not, can you try with that?  Also, what version of go are you using?

**Comment by gmarek** [comment]
released go 1.6.3, but it was a plain make from my workstation, not a dockerized build. Clean make fixed the issue, so it's not a problem that can't be mitigated. The problem is that if this would be used to build release we would release a binary that would do random things, IIUC (i.e. linking would put pointers to some strange places of dependees).

**Comment by jbeda** [comment]
I think that generally we do a clean build for releases.  But this should be fixed.  I tested a similar scenario in 1.7.1 (on my mac) and didn't repro but that could either be a delta from 1.6.3 to 1.7.1 or I didn't reproduce what you were doing well enough.  Still digging.

@thockin -- any ideas?

**Comment by jbeda** [comment]
Was able to repro in dockerized build with 1.6.3.  Doing dockerized build with 1.7.1 to isolate it.  This looks like it might be a bug that was fixed with 1.7.  There were some toolchain improvements around stale builds.

**Comment by thockin** [comment]
I'm not going to have time to look at this in the immediate term.  If you
think it is Makefile related, please scream at me...

**Comment by jbeda** [comment]
I found a bug in my dockerized build (don't mirror deleted files).

However, I can't repro this by just deleting files for a regular binary.

My test:
```
make WHAT=cmd/kubeadm
rm cmd/kubeadm/app/cmd/join.go
make WHAT=cmd/kubeadm
```

I do get an error (as expected) on the second `make`.

Perhaps this is an issue with the way we build tests.  I'll keep looking.

**Comment by jbeda** [comment]
See #34553 for PR to fix related bug in dockerized build.  That won't fix this issue though.

**Comment by luxas** [comment]
@gmarek @jbeda I guess this is fixed now, right?
I think we can close this and open new issues in case something of this still occurs.
