### ISSUE TITLE
release-1.0 branch does not compile with go-1.5.1

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#16229]
The issue is that bytes.Reader grew a Size() method, which makes a multi-embed ambiguous.  The fix is easy if we're willing to take a patch into Godeps.  Otherwise we can demand go-1.4.x ?

@brendandburns 

```
# github.com/elazarl/go-bindata-assetfs
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:74: AssetFile.Size is ambiguous
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:74: cannot use f (type *AssetFile) as type os.FileInfo in return argument:
        *AssetFile does not implement os.FileInfo (missing Size method)
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:114: AssetDirectory.Size is ambiguous
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:114: cannot use f (type *AssetDirectory) as type os.FileInfo in return argument:
        *AssetDirectory does not implement os.FileInfo (missing Size method)
# k8s.io/kubernetes/cmd/mungedocs
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/examples/k8petstore/web-server
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# github.com/onsi/ginkgo/ginkgo
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/cmd/genconversion
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/cmd/gendeepcopy
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/cmd/kube-proxy
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/cmd/kubectl
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/cmd/genman
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/cmd/gendocs
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/cmd/genbashcomp
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
# k8s.io/kubernetes/cmd/kubelet
link: warning: option -X k8s.io/kubernetes/pkg/version.gitCommit f10e6d13a6a5baacc71f82320c2c5a100e9b5111 may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitCommit=f10e6d13a6a5baacc71f82320c2c5a100e9b5111
link: warning: option -X k8s.io/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X k8s.io/kubernetes/pkg/version.gitVersion v1.0.6.25+f10e6d13a6a5ba-dirty may not work in future releases; use -X k8s.io/kubernetes/pkg/version.gitVersion=v1.0.6.25+f10e6d13a6a5ba-dirty
!!! Error in /usr/local/google/home/thockin/src/kubernetes/hack/lib/golang.sh:383
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /usr/local/google/home/thockin/src/kubernetes/hack/lib/golang.sh:383 kube::golang::build_binaries_for_platform(...)
  2: /usr/local/google/home/thockin/src/kubernetes/hack/lib/golang.sh:521 kube::golang::build_binaries(...)
  3: hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /usr/local/google/home/thockin/src/kubernetes/hack/lib/golang.sh:439
  '( kube::golang::setup_env; local version_ldflags; version_ldflags=$(kube::version::ldflags); local host_platform; host_platform=$(kube::golang::host_platform); local goflags; eval "goflags=(${KUBE_GOFLAGS:-})"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == "--use_go_build" ]]; then
        use_go_build=true;
    else
        if [[ "${arg}" == -* ]]; then
            goflags+=("${arg}");
        else
            targets+=("${arg}");
        fi;
    fi;
done; if [[ ${#targets[@]} -eq 0 ]]; then
    targets=("${KUBE_ALL_TARGETS[@]}");
fi; local -a platforms=("${KUBE_BUILD_PLATFORMS[@]:+${KUBE_BUILD_PLATFORMS[@]}}"); if [[ ${#platforms[@]} -eq 0 ]]; then
    platforms=("${host_platform}");
fi; local binaries; binaries=($(kube::golang::binaries_from_targets "${targets[@]}")); local parallel=false; if [[ ${#platforms[@]} -gt 1 ]]; then
    local gigs; gigs=$(kube::golang::get_physmem); if [[ ${gigs} -gt ${KUBE_PARALLEL_BUILD_MEMORY} ]]; then
        kube::log::status "Multiple platforms requested and available ${gigs}G > threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in parallel"; parallel=true;
    else
        kube::log::status "Multiple platforms requested, but available ${gigs}G < threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in serial"; parallel=false;
    fi;
fi; if [[ "${parallel}" == "true" ]]; then
    kube::log::status "Building go targets for ${platforms[@]} in parallel (output will appear in a burst when complete):" "${targets[@]}"; local platform; for platform in "${platforms[@]}";
    do
        ( kube::golang::set_platform_envs "${platform}"; kube::log::status "${platform}: go build started"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-}; kube::log::status "${platform}: go build finished" ) &> "/tmp//${platform//\//_}.build" &
    done; local fails=0; for job in $(jobs -p);
    do
        wait ${job} || let "fails+=1";
    done; for platform in "${platforms[@]}";
    do
        cat "/tmp//${platform//\//_}.build";
    done; exit ${fails};
else
    for platform in "${platforms[@]}";
    do
        kube::log::status "Building go targets for ${platform}:" "${targets[@]}"; kube::golang::set_platform_envs "${platform}"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-};
    done;
fi )' exited with status 1
Call stack:
  1: /usr/local/google/home/thockin/src/kubernetes/hack/lib/golang.sh:439 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1
make: *** [all] Error 1
```

**Comment by lavalamp** [comment]
It will also fail a number of unit tests. I don't think we're obligated to update 1.0 for go1.5.1, personally.

**Comment by joshk0** [comment]
Would be nice to at least update the docs to indicate that you can't use go>1.4.

**Comment by trumpcard** [comment]
I just wasted time on this. +1 for either fixing or updating the docs.

**Comment by gajju26** [comment]
@thockin  I am also facing the same issue can you please provide me a temporary workaround for this??? Please find my console log below:
link: warning: option -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitTreeState dirty may not work in future releases; use -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitTreeState=dirty
link: warning: option -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitVersion v1.0.3-dirty may not work in future releases; use -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitVersion=v1.0.3-dirty
link: warning: option -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitMajor 1 may not work in future releases; use -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitMajor=1
link: warning: option -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitMinor 0+ may not work in future releases; use -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitMinor=0+
# github.com/elazarl/go-bindata-assetfs
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:74: AssetFile.Size is ambiguous
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:74: cannot use f (type *AssetFile) as type os.FileInfo in return argument:
        *AssetFile does not implement os.FileInfo (missing Size method)
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:114: AssetDirectory.Size is ambiguous
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:114: cannot use f (type *AssetDirectory) as type os.FileInfo in return argument:
        *AssetDirectory does not implement os.FileInfo (missing Size method)
# github.com/GoogleCloudPlatform/kubernetes/cmd/kubectl
link: warning: option -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitCommit 61c6ac5f350253a4dc002aee97b7db7ff01ee4ca may not work in future releases; use -X github.com/GoogleCloudPlatform/kubernetes/pkg/version.gitCommit=61c6ac5f350253a4dc002aee97b7db7ff01ee4ca
