### PR TITLE
Dockershim remove

### PR DESCRIPTION
**Pull request by yanghesong**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Dockershim has been removed, refer to #97252. Change the corresponding error message of dockershim.
#### Which issue(s) this PR fixes:
Change the corresponding error message of dockershim.

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Change the corresponding error message of dockershim.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/security/apparmor/validate.go [hunk 1]
```diff
@@ -111,9 +111,9 @@ func validateHost(runtime string) error {
 		return errors.New("AppArmor is not enabled on the host")
 	}
 
-	// Check runtime support. Currently only Docker is supported.
-	if runtime != kubetypes.DockerContainerRuntime && runtime != kubetypes.RemoteContainerRuntime {
-		return fmt.Errorf("AppArmor is only enabled for 'docker' and 'remote' runtimes. Found: %q", runtime)
+	// Check runtime support. Currently only CRI is supported.
+	if runtime != kubetypes.RemoteContainerRuntime {
+		return fmt.Errorf("AppArmor is only enabled for 'remote' runtimes. Found: %q", runtime)
```
Comment (adisky) [inline pkg/security/apparmor/validate.go:116]: it might sense to remove the whole if conditions, as runtime can only be `remote` in context of kubelet though not sure what values runtime can have in this package

Comment (dims) [reply pkg/security/apparmor/validate.go:116]: +1 to @adisky 's suggestion.

Comment (endocrimes) [reply pkg/security/apparmor/validate.go:116]: +1, removing this check entirely seems reasonable to me.

Comment (yanghesong) [reply pkg/security/apparmor/validate.go]: thanks for your suggestion, the whole if conditions has been removed

**Comment by dims** [comment]
We need to fix the reference in kubelet.go too right?
https://cs.k8s.io/?q=NewValidator&i=nope&files=.*kubelet.*&excludeFiles=&repos=kubernetes/kubernetes

**Review by adisky — COMMENTED** [review]
@yanghesong tests are failing with
```
pkg/kubelet/kubelet.go:834:49: too many arguments in call to apparmor.NewValidator
W0107 03:39:43.384] 	have (string)
W0107 03:39:43.384] 	want ()
```

you need to update `pkg/kubelet/kubelet.go` as well

**Comment by yanghesong** [comment]
> @yanghesong tests are failing with
> 
> ```
> pkg/kubelet/kubelet.go:834:49: too many arguments in call to apparmor.NewValidator
> W0107 03:39:43.384] 	have (string)
> W0107 03:39:43.384] 	want ()
> ```
> 
> you need to update `pkg/kubelet/kubelet.go` as well



> We need to fix the reference in kubelet.go too right? https://cs.k8s.io/?q=NewValidator&i=nope&files=.*kubelet.*&excludeFiles=&repos=kubernetes/kubernetes

Thanks for the heads up, I'll correct it and retest soon.

**Comment by dims** [comment]
looks like a very bad merge @yanghesong
