### PR TITLE
client-go: restore FakeCustomStore conformance to cache.Store

### LINKED ISSUE #140965: client-go: FakeCustomStore no longer implements cache.Store after #134827
### What happened?

#134827 (merged 2025-10-23, shipped in client-go v0.36) added two methods to the `cache.Store` interface:

- `Bookmark(rv string)`
- `LastStoreSyncResourceVersion() string`

The package's own test double `cache.FakeCustomStore` (`staging/src/k8s.io/client-go/tools/cache/fake_custom_store.go`) was not updated, so it no longer satisfies `cache.Store`. Downstream test code that passes a `FakeCustomStore` where a `Store` is expected now fails to compile:

```
cannot use &cache.FakeCustomStore{...} (value of type *cache.FakeCustomStore) as cache.Store value:
	*cache.FakeCustomStore does not implement cache.Store (missing method Bookmark)
```

We hit this in the wild during KubeVirt's bump to v0.36.2 (kubevirt/kubevirt#18315) and had to add a local wrapper to keep ~10 test files compiling.

### What did you expect to happen?

`FakeCustomStore` keeps satisfying `cache.Store`. It is named and documented as a general store fake ("lets you define custom functions for store operations") and has satisfied `Store` since 2016. The new narrower `ReflectorStore` interface is not a substitute for read-path consumers (it has no `List`/`GetByKey`), and #134827 carried no deprecation signal for the fake.

### How can we reproduce it (as minimally and precisely as possible)?

```go
package main

import "k8s.io/client-go/tools/cache"

var _ cache.Store = &cache.FakeCustomStore{} // fails to compile with client-go v0.36.x
```

### Anything else we need to know?

Proposed fix (~15 lines, backward compatible): add `BookmarkFunc func(rv string)` and `LastStoreSyncResourceVersionFunc func() string` fields plus the two delegating methods (no-op / `""` when nil), matching the file's existing pattern. Happy to submit the PR.

### Kubernetes version

client-go v0.36.x (still present on master as of 2026-07-27)

/sig api-machinery
/kind bug

### PR DESCRIPTION
**Pull request by alancaldelas**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

#134827 added two methods to the `cache.Store` interface — `Bookmark(rv string)` and `LastStoreSyncResourceVersion() string` — but did not update `FakeCustomStore`, so the fake no longer satisfies `cache.Store` and downstream test code that passes a `FakeCustomStore` where a `Store` is expected fails to compile:

```
cannot use &cache.FakeCustomStore{...} (value of type *cache.FakeCustomStore) as cache.Store value:
	*cache.FakeCustomStore does not implement cache.Store (missing method Bookmark)
```

This adds the two missing func fields and delegating methods (no-op / `""` when the func is nil), following the file's existing pattern. Backward compatible: existing struct literals keep compiling unchanged.

#### Which issue(s) this PR fixes:

Fixes #140965

#### Special notes for your reviewer:

Hit in the wild during KubeVirt's bump to client-go v0.36.2 (kubevirt/kubevirt#18315), which had to carry a local wrapper to keep its test suite compiling.

#### Does this PR introduce a user-facing change?

```release-note
client-go: FakeCustomStore implements the Bookmark and LastStoreSyncResourceVersion methods added to the cache.Store interface in v0.36, so it satisfies cache.Store again
```

### CODE REVIEW

File: staging/src/k8s.io/client-go/tools/cache/fake_custom_store.go [hunk 1]
```diff
@@ -18,15 +18,17 @@ package cache
...
+	UpdateFunc                       func(obj interface{}) error
+	DeleteFunc                       func(obj interface{}) error
+	ListFunc                         func() []interface{}
+	ListKeysFunc                     func() []string
+	GetFunc                          func(obj interface{}) (item interface{}, exists bool, err error)
+	GetByKeyFunc                     func(key string) (item interface{}, exists bool, err error)
+	ReplaceFunc                      func(list []interface{}, resourceVersion string) error
+	ResyncFunc                       func() error
+	BookmarkFunc                     func(rv string)
+	LastStoreSyncResourceVersionFunc func() string
```
Comment (alaypatel07) [inline staging/src/k8s.io/client-go/tools/cache/fake_custom_store.go:31]: can you add:
```
var _ Store = &FakeCustomStore{}
```

to make sure this gets raised as compiler error in future?

Comment (liggitt) [reply staging/src/k8s.io/client-go/tools/cache/fake_custom_store.go:31]: yes please, anywhere we have an implementation we should be doing a type-assertion

**Comment by liggitt** [comment]
this needs to go into 1.37, please add the type assertion and then we'll merge it

**Comment by dims** [comment]
@alancaldelas can you please confirm you are able to make the change suggested by @liggitt

File: staging/src/k8s.io/client-go/tools/cache/fake_custom_store.go (hunk 1 above)
Comment (alaypatel07) [reply staging/src/k8s.io/client-go/tools/cache/fake_custom_store.go:31]: @liggitt for this instance the type assertion was added.

**Comment by alancaldelas** [comment]
> @alancaldelas can you please confirm you are able to make the change suggested by @liggitt 

Yes we are good to go
