### PR TITLE
Tune PreemptionAsync and Unschedulable tests threshold and params.

### LINKED ISSUE #128221: Failing ci-benchmark-scheduler-perf-master tests for PreemptionAsync and Unschedulable tests
### Which jobs are failing?

ci-benchmark-scheduler-perf-master

### Which tests are failing?

PreemptionAsync and Unschedulable test cases

### Since when has it been failing?

17th Oct 2024

### Testgrid link

https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler-perf

### Reason for failure (if possible)

PreemptionAsync test is failing because of context deadline error:
```
    scheduler_perf.go:1427: FATAL ERROR: op 3: error in waiting for pods to get scheduled: at least pod namespace-3/pod-4vfnq is not scheduled: context deadline exceeded
--- FAIL: BenchmarkPerfScheduling/PreemptionAsync/5000Node
```
Caused by #127829

Unschedulable test is failing because of too high threshold configured:
```
    scheduler_perf.go:1298: ERROR: op 2: BenchmarkPerfScheduling/Unschedulable/5kNodes/10kPods/namespace-2: expected SchedulingThroughput Average to be higher: got 289.204988, want 400.000000
--- FAIL: BenchmarkPerfScheduling/Unschedulable/5kNodes/10kPods
```
Caused by #128153
After making these changes, the threshold should be even lower, as it seems a value around 270-280 should be good at the moment.  

### Anything else we need to know?

You should ignore the first row in testgrid (k8s.io/kubernetes/test/integration/scheduler_perf.scheduler_perf), as it doesn't affect the results and check only the second one (ci-benchmark-scheduler-perf-master.Overall).

### Relevant SIG(s)

/sig scheduling

### PR DESCRIPTION
**Pull request by dom4ha**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Test machines work noticeably slower than local dev machine, so the throughput determined locally turned out to be inaccurate.

In effect in the PreemptionAsync test, the churn generated at the 20/s rate, turned out to starve out scheduling of the regular pods. Similarly the Unschedulable test was failing due to the lower throughput than the limit determined locally.

#### Which issue(s) this PR fixes:
Fixes #128221

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

File: test/integration/scheduler_perf/config/performance-config.yaml [hunk 1]
```diff
@@ -705,7 +705,7 @@
     mode: create
     templatePaths:
     - config/templates/pod-high-priority-large-cpu.yaml
-    intervalMilliseconds: 50
+    intervalMilliseconds: 200
```
Comment (sanposhiho) [inline test/integration/scheduler_perf/config/performance-config.yaml:708]: So, why did we have to increase the interval?

**Review by sanposhiho — COMMENTED** [review]
General ask: Please do not skip "What this PR does / why we need it" in the PR description. We often have to be a history digger, looking at past changes and discussions (like me at the moment). For the future us, we should clarify the changes (especially reasons) in every PR and avoid this kind of unknown changes.

I don't see why these changes could solve the failing test from the PR description nor in the issue discussion.

File: test/integration/scheduler_perf/config/performance-config.yaml (hunk 1 above)
Comment (sanposhiho) [reply test/integration/scheduler_perf/config/performance-config.yaml:708]: I'm asking this because:
- The shorter `intervalMilliseconds` is, the more likely the test would make the improvement from the async preemption more visible.
- I saw the test case passed even after reverting this change to 50.

Comment (dom4ha) [reply test/integration/scheduler_perf/config/performance-config.yaml:708]: The test running on test machines turned out to be much slower and the original rate of preemptions were starving out scheduling of regular pods completely.

You can use /test pull-kubernetes-scheduler-perf to test the performance on the test machines.

**Comment by dom4ha** [comment]
> General ask: Please do not skip "What this PR does / why we need it" in the PR description. We often have to be a history digger, looking at past changes and discussions (like me at the moment). For the future us, we should clarify the changes (especially reasons) in every PR and avoid this kind of unknown changes.
> 
> I don't see why these changes could solve the failing test from the PR description nor in the issue discussion.

Yeah, I noticed that there were no signs of troubleshooting. Updated the description.

File: test/integration/scheduler_perf/config/performance-config.yaml (hunk 1 above)
Comment (sanposhiho) [reply test/integration/scheduler_perf/config/performance-config.yaml:708]: I see, so `50` fails due to a weaker CI machine, even though my local machine is capable to handle.
