### PR TITLE
kubelet: add Windows OOM observability via CRI container statuses

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

On Windows the kubelet OOM watcher was a no-op because there is no kernel
cgroup OOM streamer (as on Linux). This PR adds a Windows implementation of
the OOM watcher that periodically reconciles CRI container statuses and
surfaces containers that crossed into the OOMKilled state.

When a container reports a terminal exit reason of `OOMKilled`, the watcher
emits a Kubernetes container OOMKilled event on the owning pod, increments the
`container_oom_events_total` counter (reusing the existing descriptor), and
keys the counter to the container's CRI ID. Each OOM-killed container is
surfaced exactly once; containers already OOMKilled when the kubelet restarts
are seeded so historical kills are not replayed.

The Windows watcher is wired into the kubelet via the existing OOM watcher
path, receiving the CRI runtime service available when the watcher is
constructed. Linux/unsupported implementations of `NewWatcher` accept (and
ignore) the new getter argument so the call site compiles across platforms.

To make the counts observable, the Windows cAdvisor client now surfaces
per-container info from the live CRI container set: the kubelet wires its
runtime service into the cadvisor client via an optional interface (a no-op on
Linux), and `GetRequestedContainersInfo` returns one minimal `ContainerInfo`
per container keyed by the CRI container ID. The watcher records each kill
under that same ID so `OOMEventsForContainer(info.Name)` matches and
`container_oom_events_total` is emitted on Windows nodes.

#### Which issue(s) this PR fixes:

Fixes #N/A

#### Special notes for your reviewer:

Based on the in-tree OOM watcher introduced in #140026. This revision also
tightens the poll behavior: each exited container status is inspected by the
CRI exactly once (exited containers never change their exit reason), so the
watcher does not re-query non-OOM exited containers every interval. The
Windows cadvisor wiring is an optional `ContainerEnumeratorSetter`; Linux
cadvisor does not implement it and the kubelet skips it, so Linux behavior is
unchanged.

Tests cover event emission, the metric counter, single-surfacing per container,
replay suppression, the nil-runtime safety path, the once-only inspection
guarantee, an end-to-end poll-loop test that drives the seed plus periodic
ticks, and a Windows cadvisor `GetRequestedContainersInfo` test using a fake
CRI enumerator. Cross compiled and vetted for linux, windows, and darwin; the
windows tests run on a Windows host.

#### Does this PR introduce a user-facing change?

```release-note
kubelet: on Windows, emit a Kubernetes event and increment the
container_oom_events_total counter when a container is terminated by the
out-of-memory killer.
```

#### AI disclosure

This PR was authored with the assistance of an AI coding agent. A human
maintainer is responsible for the correctness and content of all changes.

### CODE REVIEW

**Comment by MartinForReal** [comment]
Thanks for the review. I addressed the three findings:
- `seen`/`inspected` OOM bookkeeping is pruned against the current container list after each successful reconcile, so it stays bounded once CRI garbage collects containers.
- Reconcile waits for a successful startup seed; on a transient CRI list error the seed is retried each interval instead of replaying every surviving historical OOM as a fresh kill against an empty set.
- Synthetic per-container cadvisor records no longer advertise `HasCpu`/`HasMemory` without specs, so the incorrect `container_spec_cpu_shares=0` / `container_spec_memory_limit_bytes=0` series are gone; `container_oom_events_total` is unaffected (`OOMEventsForContainer` reads the count independently).

Committed: `c31709e2cac`.
