### ISSUE TITLE
[Failing Test] integration: scheduler_perf 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#127178]
### Which jobs are failing?

ci-kubernetes-integration-master

### Which tests are failing?

k8s.io/kubernetes/test/integration: scheduler_perf 

=== RUN   TestScheduling/TopologySpreading/500Nodes

### Since when has it been failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1828486267961085952
08-26

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
 contexthelper.go:69: 
        WARNING: test suite deadline (2024-08-27 18:38:17 +0000 UTC) is close, need to clean up before the 5s cleanup grace period
    scheduler_perf.go:1159: FATAL ERROR: op 5: error in waiting for pods to get scheduled: at least pod measure-ns-0/affinity-pod-zjnkk is not scheduled: context canceled
{"level":"warn","ts":"2024-08-27T18:38:13.667260Z","caller":"embed/serve.go:160","msg":"stopping insecure grpc server due to error","error":"accept tcp 127.0.0.1:44287: use of closed network connection"}
{"level":"warn","ts":"2024-08-27T18:38:13.667415Z","caller":"embed/serve.go:162","msg":"stopped insecure grpc server due to error","error":"accept tcp 127.0.0.1:44287: use of closed network connection"}
panic: test timed out after 10m0s
running tests:
	TestScheduling (10m0s)
	TestScheduling/SchedulingRequiredPodAffinityWithNSSelector (11s)
	TestScheduling/SchedulingRequiredPodAffinityWithNSSelector/10Nodes (11s)

goroutine 2711122 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2366 +0x385
created by time.goFunc
	/usr/local/go/src/time/sleep.go:177 +0x2d
```

### Relevant SIG(s)

/sig scheduling

**Comment by sanposhiho** [comment]
cc @macsko

**Comment by pacoxu** [comment]
It may be caused by https://github.com/kubernetes/kubernetes/pull/124003.
@carlory

**Comment by carlory** [comment]
/assign 

will take a look

**Comment by sanposhiho** [comment]
No notable activity around pod topology spread itself.
https://github.com/kubernetes/kubernetes/commits/master/pkg/scheduler/framework/plugins/podtopologyspread

**Comment by carlory** [comment]
https://github.com/kubernetes/kubernetes/pull/124003 was merged at 8-26

1. Passed (before 8-27 05:16 CST)
2. https://github.com/kubernetes/kubernetes/pull/126886 was merged at 5:23 CST 
3. Failed (since 8-27 06:21 CST)

![image](https://github.com/user-attachments/assets/52ffab8e-9403-4ebe-a6d6-9dc4f822f574)

cc @pohly Is it related to https://github.com/kubernetes/kubernetes/commit/cc9234cffdbcc1de0eb6e1a319b853dc7f759f2b?

**Comment by macsko** [comment]
> Now there's a timeout of 10 minutes

It's a different timeout configured within a scheduler_perf, while waiting for pods to be scheduled ([ref](https://github.com/kubernetes/kubernetes/blob/2108e54f5249c6b3b0c9f824314cb5f33c01e3f4/test/integration/scheduler_perf/scheduler_perf.go#L1440)). It means that we have some issue with pods scheduling.

**Comment by pohly** [comment]
That's a different 10 minute timeout.

I'm referring to this:
```
WARNING: test suite deadline (2024-09-06 09:22:29 +0000 UTC) is close, need to clean up before the 5s cleanup grace period
```

That is based on the deadline in the `testing.T`, which in turn is derived from the `go test -timeout` parameter.

**Comment by pohly** [comment]
The main question is: why are we running for more than 10 minutes? I thought we were faster than that now.

**Comment by macsko** [comment]
We have added smaller workloads for all test cases, but also we run the mid-sized integration-test labeled workloads (according to the [comment](https://github.com/kubernetes/kubernetes/pull/126352#discussion_r1717497197)). I think these mid-sized workloads increased testing time the most.

**Comment by pohly** [comment]
On my machine: `gotestsum ./test/integration/scheduler_perf/`
* master = 1dbf0830c59 = 565.997s

That's too close to 10 minutes, assuming that the CI isn't significantly faster. I hadn't enabled enough output to tell what it ran.

**Comment by macsko** [comment]
I think we need to remember that we also run other tests apart from scheduler_perf with limited resources. In my case integration tests with `KUBE_INTEGRATION_TEST_MAX_CONCURRENCY=1` runs for 871.591s.

**Comment by pohly** [comment]
I think the fallacy in https://github.com/kubernetes/kubernetes/pull/126352#discussion_r1717497197 was that it assumed that a longer runtime would be okay for the periodic job. In a way it is, but there's still this 10 minute limit.

Speaking of which, I am not sure yet where it comes from. Perhaps it's really simply this default:
```
hack/make-rules/test-integration.sh:KUBE_TIMEOUT=${KUBE_TIMEOUT:--timeout=600s}
```

Let's try to get below those 10 minutes. We just need to be a bit more selective. @macsko, can you work on this?

**Comment by macsko** [comment]
Sure, I can try to limit the time to 10 minutes and we'll see what happen.

**Comment by macsko** [comment]
Issue seems to be resolved by #127238.

/close

**Comment by carlory** [comment]
/reopen 

It's failing again after https://github.com/kubernetes/kubernetes/compare/f83677354...1d3c003c8?

https://github.com/kubernetes/kubernetes/commit/c1f7b8e9f1209f347a7903419c914589693629d1 may be the cause. /cc @macsko

**Comment by macsko** [comment]
Looks like it's a timeout again. I'll reduce the number of test cases running as integration.

**Comment by drewhagen** [comment]
Thanks for the help! Builds are mostly green again since that PR.

It looks like the scheduler_perf test has flaked a few times since then, notably today (9/15) with the same error:

"stopping insecure grpc server due to error"
with the commit
https://github.com/kubernetes/kubernetes/commit/af2bf2d8f1b3437fe67e1686266a176320422465. 1 failure / 6 runs for that same commit.

Prow:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1835375660550328320

@kubernetes/release-team-release-signal will observe this for a bit.

**Comment by drewhagen** [comment]
it looks like scheduler_perf has been green. I think we can close this for now and reopen if it becomes an issue again.
