### ISSUE TITLE
Build error  with 'undefined: elliptic.P224' on RHEL/Fedora

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#29534]
When build latest k8s on rhel/fedora env, always failed with error

```
vendor/github.com/google/certificate-transparency/go/x509/x509.go:342: undefined: elliptic.P224
vendor/github.com/google/certificate-transparency/go/x509/x509.go:355: undefined: elliptic.P224
vendor/github.com/google/certificate-transparency/go/x509/x509.go:1461: undefined: elliptic.P224
```

detail build info: https://paste.fedoraproject.org/395191/69424585/
My go version is go1.6.2 linux/amd64
I notice there is known issue about golang on rhel https://bugzilla.redhat.com/show_bug.cgi?id=1038683

**Comment by mdshuai** [comment]
@ncdc Could you help check the problem, now I can't build latest k8s on aws instance to test.

**Comment by rootfs** [comment]
also hit this issue on Fedora 24

**Comment by ncdc** [comment]
We're working on it. For now, you can use travis-ci/gimme.

**Comment by wattsteve** [comment]
yep, also hitting this issue on Fedora 24

**Comment by rootfs** [comment]
happened to my setup with golang 1.6.3.
upgrading to golang 1.7 fixed this issue.

**Comment by cben** [comment]
- Confirmed working on F24 with go 1.7 installed by travis-ci/gimme.

- However golang-1.7-0.1.rc2.fc25.x86_64 package from rawhide:
  ```
  sudo dnf install --enablerepo rawhide golang --best
  ```
  fails with same `undefined: elliptic.P224` error.

  * It did compile, apparently works, passes `make test` with the patch from https://bugzilla.redhat.com/show_bug.cgi?id=1038683#c21 to vendor/github.com/google/certificate-transparency/go/x509/x509.go

**Comment by Sn0rt** [comment]
not from offical repo...

**Comment by dims** [comment]
Looks like there's a bug with status 'assigned' : https://bugzilla.redhat.com/show_bug.cgi?id=1379484

**Comment by mdshuai** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1379484 fixed.
Fixed In Version:  golang-1.7.3-2.fc25 golang-1.5.4-4.fc23 golang-1.6.3-4.fc24 golang-1.7.3-2.el6
