### ISSUE TITLE
kubernetes-e2e-gke Timed out waiting for cluster initialization

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#21450]
@jlowdermilk

Not sure if this is a dupe of #21322 or #21411 Has a different error message but also issue caused by the cluster not coming up: kubernetes-e2e-gke/1241
>
...
Creating cluster jenkins-e2e.../                              
Creating cluster jenkins-e2e...done.
19:21:44 ERROR: (gcloud.container.clusters.create) Operation [<Operation
19:21:44  name: u'operation-1455764417735-623e12c5'
19:21:44  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
19:21:44  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/249458424157/zones/us-central1-f/operations/operation-1455764417735-623e12c5'
19:21:44  status: StatusValueValuesEnum(DONE, 3)
19:21:44  statusMessage: u'Timed out waiting for cluster initialization. Cluster API may not be available.'
19:21:44  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/249458424157/zones/us-central1-f/clusters/jenkins-e2e'
19:21:44  zone: u'us-central1-f'>] finished with error: Timed out waiting for cluster initialization. Cluster API may not be available. 
19:21:45 2016/02/17 19:21:45 e2e.go:307: Error running up: exit status 1
19:21:45 2016/02/17 19:21:45 e2e.go:303: Step 'up' finished in 21m31.129575171s
19:21:45 
2016/02/17 19:21:45 e2e.go:141: Error starting e2e cluster. Aborting.

full log:
[e2e-gke-flake-2.txt](https://github.com/kubernetes/kubernetes/files/135628/e2e-gke-flake-2.txt)

**Comment by pwittrock** [comment]
@jlowdermilk let me know if there is someone better to assign this to.  Just saw a couple more flakes this morning.

**Comment by jlowdermilk** [comment]
I managed to get a repro of this. It looks like docker on the nodes got hosed after upgrading to 1.9.1. From /var/log/docker.log on a node
```
Warning: '-d' is deprecated, it will be removed soon. See usage.
Warning: '-r' is deprecated, it will be removed soon. See usage.
time="2016-02-18T19:35:52Z" level=warning msg="please use 'docker daemon' instead." 
time="2016-02-18T19:35:52.049264409Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)" 
time="2016-02-18T19:35:52.084339041Z" level=info msg="[graphdriver] using prior storage driver \"aufs\"" 
time="2016-02-18T19:35:52.106351149Z" level=info msg="Option DefaultDriver: bridge" 
time="2016-02-18T19:35:52.106525509Z" level=info msg="Option DefaultNetwork: bridge" 
time="2016-02-18T19:35:52.165129859Z" level=warning msg="Running modprobe bridge nf_nat br_netfilter failed with message: WARNING: Module br_netfilter not found.\ninsmod /lib/modules/3.16.0-4-amd64/kernel/net/llc/llc.ko \ninsmod /lib/modules/3.16.0-4-amd64/kernel/net/802/stp.ko \ninsmod /lib/modules/3.16.0-4-amd64/kernel/net/bridge/bridge.ko \ninsmod /lib/modules/3.16.0-4-amd64/kernel/net/netfilter/nf_conntrack.ko \ninsmod /lib/modules/3.16.0-4-amd64/kernel/net/netfilter/nf_nat.ko \n, error: exit status 1" 
time="2016-02-18T19:35:52.487247032Z" level=warning msg="Your kernel does not support swap memory limit." 
time="2016-02-18T19:35:52.487382371Z" level=warning msg="Your kernel does not support cgroup cfs period" 
time="2016-02-18T19:35:52.487402851Z" level=warning msg="Your kernel does not support cgroup cfs quotas" 
time="2016-02-18T19:35:52.487717265Z" level=info msg="Loading containers: start." 

time="2016-02-18T19:35:52.487905068Z" level=info msg="Loading containers: done." 
time="2016-02-18T19:35:52.487922370Z" level=info msg="Daemon has completed initialization" 
time="2016-02-18T19:35:52.487939879Z" level=info msg="Docker daemon" commit=f4bf5c7 execdriver=native-0.2 graphdriver=aufs version=1.8.3 
time="2016-02-18T19:35:56.296671710Z" level=info msg="GET /info" 
time="2016-02-18T19:35:56.417682039Z" level=info msg="GET /version" 
time="2016-02-18T19:35:56.452788739Z" level=info msg="GET /info" 
time="2016-02-18T19:35:56.459336508Z" level=info msg="GET /version" 
time="2016-02-18T19:35:56.460476464Z" level=info msg="GET /containers/json?all=1" 
time="2016-02-18T19:35:56.467723195Z" level=info msg="GET /images/json" 
time="2016-02-18T19:35:56.471032059Z" level=info msg="GET /containers/json?all=1" 
time="2016-02-18T19:35:56.551073281Z" level=info msg="GET /version" 
time="2016-02-18T19:35:56.566243021Z" level=info msg="GET /images/json" 
time="2016-02-18T19:35:56.567940075Z" level=info msg="GET /containers/json?all=1" 
time="2016-02-18T19:35:56.568637828Z" level=info msg="GET /info" 
time="2016-02-18T19:35:56.572330130Z" level=info msg="GET /info" 
time="2016-02-18T19:35:56.573522529Z" level=info msg="GET /version" 
time="2016-02-18T19:35:56.573915371Z" level=info msg="GET /images/json" 
time="2016-02-18T19:35:56.577042838Z" level=info msg="GET /containers/kubelet/json" 
time="2016-02-18T19:35:56.577224777Z" level=error msg="Handler for GET /containers/{name:.*}/json returned error: no such id: kubelet" 
time="2016-02-18T19:35:56.577258306Z" level=error msg="HTTP Error" err="no such id: kubelet" statusCode=404 
time="2016-02-18T19:35:56.618238892Z" level=info msg="GET /version" 
time="2016-02-18T19:35:56.634610073Z" level=info msg="GET /containers/docker-daemon/json" 
time="2016-02-18T19:35:56.634977491Z" level=error msg="Handler for GET /containers/{name:.*}/json returned error: no such id: docker-daemon" 
time="2016-02-18T19:35:56.635010649Z" level=error msg="HTTP Error" err="no such id: docker-daemon" statusCode=404 
time="2016-02-18T19:36:01.213086095Z" level=info msg="GET /version" 
time="2016-02-18T19:36:06.214214591Z" level=info msg="GET /version" 
time="2016-02-18T19:36:11.215323844Z" level=info msg="GET /version" 
time="2016-02-18T19:36:16.216444083Z" level=info msg="GET /version" 
time="2016-02-18T19:36:21.217523464Z" level=info msg="GET /version" 
time="2016-02-18T19:36:26.218468314Z" level=info msg="GET /version" 
time="2016-02-18T19:36:31.219541523Z" level=info msg="GET /version" 
time="2016-02-18T19:36:36.220475737Z" level=info msg="GET /version" 
time="2016-02-18T19:36:41.221575011Z" level=info msg="GET /version" 
time="2016-02-18T19:36:46.222648299Z" level=info msg="GET /version" 
time="2016-02-18T19:36:51.223676989Z" level=info msg="GET /version" 
time="2016-02-18T19:36:56.055407311Z" level=info msg="GET /containers/json?all=1" 
time="2016-02-18T19:36:56.224686456Z" level=info msg="GET /version" 
time="2016-02-18T19:37:01.225765191Z" level=info msg="GET /version" 
time="2016-02-18T19:37:06.226739930Z" level=info msg="GET /version" 
/usr/bin/docker already running.
time="2016-02-18T19:37:10.237426804Z" level=info msg="Processing signal 'terminated'" 
time="2016-02-18T19:37:10.452659686Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:37:11.333518064Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:37:19.783645718Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:37:26.321106823Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:37:41.367695550Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:37:56.423373670Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:38:11.469636108Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:38:20.879393345Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:38:26.524012436Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:38:41.575296997Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:38:56.630041735Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:39:11.685969760Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:39:21.940753607Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:39:26.742019040Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:39:41.795085906Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:39:56.848508840Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:40:11.902383269Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:40:23.003350788Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:40:26.953819673Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:40:42.013413512Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:40:57.064287394Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:41:12.116799604Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:41:24.070699915Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:41:27.170296138Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:41:42.228659719Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:41:57.279283908Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:42:12.336346622Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:42:25.133502107Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:42:27.387745941Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:42:42.439306232Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:42:57.495192973Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:43:12.562251332Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:43:26.200437440Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:43:27.616919669Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:43:42.666880383Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:43:57.722130233Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:44:12.772429647Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:44:27.258172554Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:44:27.827214034Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:44:42.878871990Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:44:57.937267884Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:45:12.988474481Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:45:28.049089754Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:45:28.328010064Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:45:43.102461133Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually" 
time="2016-02-18T19:45:58.153888119Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: bridge device with non default name cbr0 must be created manually"
```

**Comment by jlowdermilk** [comment]
cc @dchen1107

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/issues/21261#issuecomment-185445866 ?

**Comment by dchen1107** [comment]
@jlowdermilk I read your last comment above, I believe this is dup of https://github.com/kubernetes/kubernetes/issues/20995

**Comment by jlowdermilk** [comment]
Closing as dupe of #20995
